In [40]:
import pandas as pd
df = pd.read_csv(r'C:\Users\User\Documents\GitHub\AIforBioinformatics\dataset\transposed_GDS3257.csv')

C:\Users\User\AppData\Local\Temp\ipykernel_17728\1602678587.py:2: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074,1075,1076,1077,1078,1079,1080,1081,1082,1083,1084,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094,1095,1096,1097,1098,1099,1100,1101,1102,1103,1104,1105,1106,1107,1108,1109,1110,1111,1112,1113,1114,1115,1116,1117,1118,1119,1120,1121,1122,1123,1124,1125,1126,1127,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1141,1142,1143,1144,1145,1146,1147,1148,1149,1150,1151,1152,1153,1154,1155,1156,1157,1158,1159,1160,1161,1162,1163,1164,1165,1166,1167,1168,1169,1170,1171,1172,1173,1174,1175,1176,1177,1178,1179,1180,1181,1182,1183,1184,1185,1186,1187,1188,1189,1190,1191,1192,1193,1194,1195,1196,1197,1198,1199,1200,1201,1202,1203,1204,1205,1206,1207,1208,1209,1210,1211,1212,1213,1214,1215,1216,1217,1218,1219,1220,1221,1222,1223,1224,1225,1226,1227,1228,1229,1230,1231,1232,1233,1234,1235,1236,1237,1238,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1252,1253,1254,1255,1256,1257,1258,1259,1260,1261,1262,1263,1264,1265,1266,1267,1268,1269,1270,1271,1272,1273,1274,1275,1276,1277,1278,1279,1280,1281,1282,1283,1284,1285,1286,1287,1288,1289,1290,1291,1292,1293,1294,1295,1296,1297,1298,1299,1300,1301,1302,1303,1304,1305,1306,1307,1308,1309,1310,1311,1312,1313,1314,1315,1316,1317,1318,1319,1320,1321,1322,1323,1324,1325,1326,1327,1328,1329,1330,1331,1332,1333,1334,1335,1336,1337,1338,1339,1340,1341,1342,1343,1344,1345,1346,1347,1348,1349,1350,1351,1352,1353,1354,1355,1356,1357,1358,1359,1360,1361,1362,1363,1364,1365,1366,1367,1368,1369,1370,1371,1372,1373,1374,1375,1376,1377,1378,1379,1380,1381,1382,1383,1384,1385,1386,1387,1388,1389,1390,1391,1392,1393,1394,1395,1396,1397,1398,1399,1400,1401,1402,1403,1404,1405,1406,1407,1408,1409,1410,1411,1412,1413,1414,1415,1416,1417,1418,1419,1420,1421,1422,1423,1424,1425,1426,1427,1428,1429,1430,1431,1432,1433,1434,1435,1436,1437,1438,1439,1440,1441,1442,1443,1444,1445,1446,1447,1448,1449,1450,1451,1452,1453,1454,1455,1456,1457,1458,1459,1460,1461,1462,1463,1464,1465,1466,1467,1468,1469,1470,1471,1472,1473,1474,1475,1476,1477,1478,1479,1480,1481,1482,1483,1484,1485,1486,1487,1488,1489,1490,1491,1492,1493,1494,1495,1496,1497,1498,1499,1500,1501,1502,1503,1504,1505,1506,1507,1508,1509,1510,1511,1512,1513,1514,1515,1516,1517,1518,1519,1520,1521,1522,1523,1524,1525,1526,1527,1528,1529,1530,1531,1532,1533,1534,1535,1536,1537,1538,1539,1540,1541,1542,1543,1544,1545,1546,1547,1548,1549,1550,1551,1552,1553,1554,1555,1556,1557,1558,1559,1560,1561,1562,1563,1564,1565,1566,1567,1568,1569,1570,1571,1572,1573,1574,1575,1576,1577,1578,1579,1580,1581,1582,1583,1584,1585,1586,1587,1588,1589,1590,1591,1592,1593,1594,1595,1596,1597,1598,1599,1600,1601,1602,1603,1604,1605,1606,1607,1608,1609,1610,1611,1612,1613,1614,1615,1616,1617,1618,1619,1620,1621,1622,1623,1624,1625,1626,1627,1628,1629,1630,1631,1632,1633,1634,1635,1636,1637,1638,1639,1640,1641,1642,1643,1644,1645,1646,1647,1648,1649,1650,1651,1652,1653,1654,1655,1656,1657,1658,1659,1660,1661,1662,1663,1664,1665,1666,1667,1668,1669,1670,1671,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682,1683,1684,1685,1686,1687,1688,1689,1690,1691,1692,1693,1694,1695,1696,1697,1698,1699,1700,1701,1702,1703,1704,1705,1706,1707,1708,1709,1710,1711,1712,1713,1714,1715,1716,1717,1718,1719,1720,1721,1722,1723,1724,1725,1726,1727,1728,1729,1730,1731,1732,1733,1734,1735,1736,1737,1738,1739,1740,1741,1742,1743,1744,1745,1746,1747,1748,1749,1750,1751,1752,1753,1754,1755,1756,1757,1758,1759,1760,1761,1762,1763,1764,1765,1766,1767,1768,1769,1770,1771,1772,1773,1774,1775,1776,1777,1778,1779,1780,1781,1782,1783,1784,1785,1786,1787,1788,1789,1790,1791,1792,1793,1794,1795,1796,1797,1798,1799,1800,1801,1802,1803,1804,1805,1806,1807,1808,1809,1810,1811,1812,1813,1814,1815,1816,1817,1818,1819,1820,1821,1822,1823,1824,1825,1826,1827,1828,1829,1830,1831,1832,1833,1834,1835,1836,1837,1838,1839,1840,1841,1842,1843,1844,1845,1846,1847,1848,1849,1850,1851,1852,1853,1854,1855,1856,1857,1858,1859,1860,1861,1862,1863,1864,1865,1866,1867,1868,1869,1870,1871,1872,1873,1874,1875,1876,1877,1878,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1899,1900,1901,1902,1903,1904,1905,1906,1907,1908,1909,1910,1911,1912,1913,1914,1915,1916,1917,1918,1919,1920,1921,1922,1923,1924,1925,1926,1927,1928,1929,1930,1931,1932,1933,1934,1935,1936,1937,1938,1939,1940,1941,1942,1943,1944,1945,1946,1947,1948,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035,2036,2037,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047,2048,2049,2050,2051,2052,2053,2054,2055,2056,2057,2058,2059,2060,2061,2062,2063,2064,2065,2066,2067,2068,2069,2070,2071,2072,2073,2074,2075,2076,2077,2078,2079,2080,2081,2082,2083,2084,2085,2086,2087,2088,2089,2090,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100,2101,2102,2103,2104,2105,2106,2107,2108,2109,2110,2111,2112,2113,2114,2115,2116,2117,2118,2119,2120,2121,2122,2123,2124,2125,2126,2127,2128,2129,2130,2131,2132,2133,2134,2135,2136,2137,2138,2139,2140,2141,2142,2143,2144,2145,2146,2147,2148,2149,2150,2151,2152,2153,2154,2155,2156,2157,2158,2159,2160,2161,2162,2163,2164,2165,2166,2167,2168,2169,2170,2171,2172,2173,2174,2175,2176,2177,2178,2179,2180,2181,2182,2183,2184,2185,2186,2187,2188,2189,2190,2191,2192,2193,2194,2195,2196,2197,2198,2199,2200,2201,2202,2203,2204,2205,2206,2207,2208,2209,2210,2211,2212,2213,2214,2215,2216,2217,2218,2219,2220,2221,2222,2223,2224,2225,2226,2227,2228,2229,2230,2231,2232,2233,2234,2235,2236,2237,2238,2239,2240,2241,2242,2243,2244,2245,2246,2247,2248,2249,2250,2251,2252,2253,2254,2255,2256,2257,2258,2259,2260,2261,2262,2263,2264,2265,2266,2267,2268,2269,2270,2271,2272,2273,2274,2275,2276,2277,2278,2279,2280,2281,2282,2283,2284,2285,2286,2287,2288,2289,2290,2291,2292,2293,2294,2295,2296,2297,2298,2299,2300,2301,2302,2303,2304,2305,2306,2307,2308,2309,2310,2311,2312,2313,2314,2315,2316,2317,2318,2319,2320,2321,2322,2323,2324,2325,2326,2327,2328,2329,2330,2331,2332,2333,2334,2335,2336,2337,2338,2339,2340,2341,2342,2343,2344,2345,2346,2347,2348,2349,2350,2351,2352,2353,2354,2355,2356,2357,2358,2359,2360,2361,2362,2363,2364,2365,2366,2367,2368,2369,2370,2371,2372,2373,2374,2375,2376,2377,2378,2379,2380,2381,2382,2383,2384,2385,2386,2387,2388,2389,2390,2391,2392,2393,2394,2395,2396,2397,2398,2399,2400,2401,2402,2403,2404,2405,2406,2407,2408,2409,2410,2411,2412,2413,2414,2415,2416,2417,2418,2419,2420,2421,2422,2423,2424,2425,2426,2427,2428,2429,2430,2431,2432,2433,2434,2435,2436,2437,2438,2439,2440,2441,2442,2443,2444,2445,2446,2447,2448,2449,2450,2451,2452,2453,2454,2455,2456,2457,2458,2459,2460,2461,2462,2463,2464,2465,2466,2467,2468,2469,2470,2471,2472,2473,2474,2475,2476,2477,2478,2479,2480,2481,2482,2483,2484,2485,2486,2487,2488,2489,2490,2491,2492,2493,2494,2495,2496,2497,2498,2499,2500,2501,2502,2503,2504,2505,2506,2507,2508,2509,2510,2511,2512,2513,2514,2515,2516,2517,2518,2519,2520,2521,2522,2523,2524,2525,2526,2527,2528,2529,2530,2531,2532,2533,2534,2535,2536,2537,2538,2539,2540,2541,2542,2543,2544,2545,2546,2547,2548,2549,2550,2551,2552,2553,2554,2555,2556,2557,2558,2559,2560,2561,2562,2563,2564,2565,2566,2567,2568,2569,2570,2571,2572,2573,2574,2575,2576,2577,2578,2579,2580,2581,2582,2583,2584,2585,2586,2587,2588,2589,2590,2591,2592,2593,2594,2595,2596,2597,2598,2599,2600,2601,2602,2603,2604,2605,2606,2607,2608,2609,2610,2611,2612,2613,2614,2615,2616,2617,2618,2619,2620,2621,2622,2623,2624,2625,2626,2627,2628,2629,2630,2631,2632,2633,2634,2635,2636,2637,2638,2639,2640,2641,2642,2643,2644,2645,2646,2647,2648,2649,2650,2651,2652,2653,2654,2655,2656,2657,2658,2659,2660,2661,2662,2663,2664,2665,2666,2667,2668,2669,2670,2671,2672,2673,2674,2675,2676,2677,2678,2679,2680,2681,2682,2683,2684,2685,2686,2687,2688,2689,2690,2691,2692,2693,2694,2695,2696,2697,2698,2699,2700,2701,2702,2703,2704,2705,2706,2707,2708,2709,2710,2711,2712,2713,2714,2715,2716,2717,2718,2719,2720,2721,2722,2723,2724,2725,2726,2727,2728,2729,2730,2731,2732,2733,2734,2735,2736,2737,2738,2739,2740,2741,2742,2743,2744,2745,2746,2747,2748,2749,2750,2751,2752,2753,2754,2755,2756,2757,2758,2759,2760,2761,2762,2763,2764,2765,2766,2767,2768,2769,2770,2771,2772,2773,2774,2775,2776,2777,2778,2779,2780,2781,2782,2783,2784,2785,2786,2787,2788,2789,2790,2791,2792,2793,2794,2795,2796,2797,2798,2799,2800,2801,2802,2803,2804,2805,2806,2807,2808,2809,2810,2811,2812,2813,2814,2815,2816,2817,2818,2819,2820,2821,2822,2823,2824,2825,2826,2827,2828,2829,2830,2831,2832,2833,2834,2835,2836,2837,2838,2839,2840,2841,2842,2843,2844,2845,2846,2847,2848,2849,2850,2851,2852,2853,2854,2855,2856,2857,2858,2859,2860,2861,2862,2863,2864,2865,2866,2867,2868,2869,2870,2871,2872,2873,2874,2875,2876,2877,2878,2879,2880,2881,2882,2883,2884,2885,2886,2887,2888,2889,2890,2891,2892,2893,2894,2895,2896,2897,2898,2899,2900,2901,2902,2903,2904,2905,2906,2907,2908,2909,2910,2911,2912,2913,2914,2915,2916,2917,2918,2919,2920,2921,2922,2923,2924,2925,2926,2927,2928,2929,2930,2931,2932,2933,2934,2935,2936,2937,2938,2939,2940,2941,2942,2943,2944,2945,2946,2947,2948,2949,2950,2951,2952,2953,2954,2955,2956,2957,2958,2959,2960,2961,2962,2963,2964,2965,2966,2967,2968,2969,2970,2971,2972,2973,2974,2975,2976,2977,2978,2979,2980,2981,2982,2983,2984,2985,2986,2987,2988,2989,2990,2991,2992,2993,2994,2995,2996,2997,2998,2999,3000,3001,3002,3003,3004,3005,3006,3007,3008,3009,3010,3011,3012,3013,3014,3015,3016,3017,3018,3019,3020,3021,3022,3023,3024,3025,3026,3027,3028,3029,3030,3031,3032,3033,3034,3035,3036,3037,3038,3039,3040,3041,3042,3043,3044,3045,3046,3047,3048,3049,3050,3051,3052,3053,3054,3055,3056,3057,3058,3059,3060,3061,3062,3063,3064,3065,3066,3067,3068,3069,3070,3071,3072,3073,3074,3075,3076,3077,3078,3079,3080,3081,3082,3083,3084,3085,3086,3087,3088,3089,3090,3091,3092,3093,3094,3095,3096,3097,3098,3099,3100,3101,3102,3103,3104,3105,3106,3107,3108,3109,3110,3111,3112,3113,3114,3115,3116,3117,3118,3119,3120,3121,3122,3123,3124,3125,3126,3127,3128,3129,3130,3131,3132,3133,3134,3135,3136,3137,3138,3139,3140,3141,3142,3143,3144,3145,3146,3147,3148,3149,3150,3151,3152,3153,3154,3155,3156,3157,3158,3159,3160,3161,3162,3163,3164,3165,3166,3167,3168,3169,3170,3171,3172,3173,3174,3175,3176,3177,3178,3179,3180,3181,3182,3183,3184,3185,3186,3187,3188,3189,3190,3191,3192,3193,3194,3195,3196,3197,3198,3199,3200,3201,3202,3203,3204,3205,3206,3207,3208,3209,3210,3211,3212,3213,3214,3215,3216,3217,3218,3219,3220,3221,3222,3223,3224,3225,3226,3227,3228,3229,3230,3231,3232,3233,3234,3235,3236,3237,3238,3239,3240,3241,3242,3243,3244,3245,3246,3247,3248,3249,3250,3251,3252,3253,3254,3255,3256,3257,3258,3259,3260,3261,3262,3263,3264,3265,3266,3267,3268,3269,3270,3271,3272,3273,3274,3275,3276,3277,3278,3279,3280,3281,3282,3283,3284,3285,3286,3287,3288,3289,3290,3291,3292,3293,3294,3295,3296,3297,3298,3299,3300,3301,3302,3303,3304,3305,3306,3307,3308,3309,3310,3311,3312,3313,3314,3315,3316,3317,3318,3319,3320,3321,3322,3323,3324,3325,3326,3327,3328,3329,3330,3331,3332,3333,3334,3335,3336,3337,3338,3339,3340,3341,3342,3343,3344,3345,3346,3347,3348,3349,3350,3351,3352,3353,3354,3355,3356,3357,3358,3359,3360,3361,3362,3363,3364,3365,3366,3367,3368,3369,3370,3371,3372,3373,3374,3375,3376,3377,3378,3379,3380,3381,3382,3383,3384,3385,3386,3387,3388,3389,3390,3391,3392,3393,3394,3395,3396,3397,3398,3399,3400,3401,3402,3403,3404,3405,3406,3407,3408,3409,3410,3411,3412,3413,3414,3415,3416,3417,3418,3419,3420,3421,3422,3423,3424,3425,3426,3427,3428,3429,3430,3431,3432,3433,3434,3435,3436,3437,3438,3439,3440,3441,3442,3443,3444,3445,3446,3447,3448,3449,3450,3451,3452,3453,3454,3455,3456,3457,3458,3459,3460,3461,3462,3463,3464,3465,3466,3467,3468,3469,3470,3471,3472,3473,3474,3475,3476,3477,3478,3479,3480,3481,3482,3483,3484,3485,3486,3487,3488,3489,3490,3491,3492,3493,3494,3495,3496,3497,3498,3499,3500,3501,3502,3503,3504,3505,3506,3507,3508,3509,3510,3511,3512,3513,3514,3515,3516,3517,3518,3519,3520,3521,3522,3523,3524,3525,3526,3527,3528,3529,3530,3531,3532,3533,3534,3535,3536,3537,3538,3539,3540,3541,3542,3543,3544,3545,3546,3547,3548,3549,3550,3551,3552,3553,3554,3555,3556,3557,3558,3559,3560,3561,3562,3563,3564,3565,3566,3567,3568,3569,3570,3571,3572,3573,3574,3575,3576,3577,3578,3579,3580,3581,3582,3583,3584,3585,3586,3587,3588,3589,3590,3591,3592,3593,3594,3595,3596,3597,3598,3599,3600,3601,3602,3603,3604,3605,3606,3607,3608,3609,3610,3611,3612,3613,3614,3615,3616,3617,3618,3619,3620,3621,3622,3623,3624,3625,3626,3627,3628,3629,3630,3631,3632,3633,3634,3635,3636,3637,3638,3639,3640,3641,3642,3643,3644,3645,3646,3647,3648,3649,3650,3651,3652,3653,3654,3655,3656,3657,3658,3659,3660,3661,3662,3663,3664,3665,3666,3667,3668,3669,3670,3671,3672,3673,3674,3675,3676,3677,3678,3679,3680,3681,3682,3683,3684,3685,3686,3687,3688,3689,3690,3691,3692,3693,3694,3695,3696,3697,3698,3699,3700,3701,3702,3703,3704,3705,3706,3707,3708,3709,3710,3711,3712,3713,3714,3715,3716,3717,3718,3719,3720,3721,3722,3723,3724,3725,3726,3727,3728,3729,3730,3731,3732,3733,3734,3735,3736,3737,3738,3739,3740,3741,3742,3743,3744,3745,3746,3747,3748,3749,3750,3751,3752,3753,3754,3755,3756,3757,3758,3759,3760,3761,3762,3763,3764,3765,3766,3767,3768,3769,3770,3771,3772,3773,3774,3775,3776,3777,3778,3779,3780,3781,3782,3783,3784,3785,3786,3787,3788,3789,3790,3791,3792,3793,3794,3795,3796,3797,3798,3799,3800,3801,3802,3803,3804,3805,3806,3807,3808,3809,3810,3811,3812,3813,3814,3815,3816,3817,3818,3819,3820,3821,3822,3823,3824,3825,3826,3827,3828,3829,3830,3831,3832,3833,3834,3835,3836,3837,3838,3839,3840,3841,3842,3843,3844,3845,3846,3847,3848,3849,3850,3851,3852,3853,3854,3855,3856,3857,3858,3859,3860,3861,3862,3863,3864,3865,3866,3867,3868,3869,3870,3871,3872,3873,3874,3875,3876,3877,3878,3879,3880,3881,3882,3883,3884,3885,3886,3887,3888,3889,3890,3891,3892,3893,3894,3895,3896,3897,3898,3899,3900,3901,3902,3903,3904,3905,3906,3907,3908,3909,3910,3911,3912,3913,3914,3915,3916,3917,3918,3919,3920,3921,3922,3923,3924,3925,3926,3927,3928,3929,3930,3931,3932,3933,3934,3935,3936,3937,3938,3939,3940,3941,3942,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952,3953,3954,3955,3956,3957,3958,3959,3960,3961,3962,3963,3964,3965,3966,3967,3968,3969,3970,3971,3972,3973,3974,3975,3976,3977,3978,3979,3980,3981,3982,3983,3984,3985,3986,3987,3988,3989,3990,3991,3992,3993,3994,3995,3996,3997,3998,3999,4000,4001,4002,4003,4004,4005,4006,4007,4008,4009,4010,4011,4012,4013,4014,4015,4016,4017,4018,4019,4020,4021,4022,4023,4024,4025,4026,4027,4028,4029,4030,4031,4032,4033,4034,4035,4036,4037,4038,4039,4040,4041,4042,4043,4044,4045,4046,4047,4048,4049,4050,4051,4052,4053,4054,4055,4056,4057,4058,4059,4060,4061,4062,4063,4064,4065,4066,4067,4068,4069,4070,4071,4072,4073,4074,4075,4076,4077,4078,4079,4080,4081,4082,4083,4084,4085,4086,4087,4088,4089,4090,4091,4092,4093,4094,4095,4096,4097,4098,4099,4100,4101,4102,4103,4104,4105,4106,4107,4108,4109,4110,4111,4112,4113,4114,4115,4116,4117,4118,4119,4120,4121,4122,4123,4124,4125,4126,4127,4128,4129,4130,4131,4132,4133,4134,4135,4136,4137,4138,4139,4140,4141,4142,4143,4144,4145,4146,4147,4148,4149,4150,4151,4152,4153,4154,4155,4156,4157,4158,4159,4160,4161,4162,4163,4164,4165,4166,4167,4168,4169,4170,4171,4172,4173,4174,4175,4176,4177,4178,4179,4180,4181,4182,4183,4184,4185,4186,4187,4188,4189,4190,4191,4192,4193,4194,4195,4196,4197,4198,4199,4200,4201,4202,4203,420

In [41]:
df.loc[df.index[1:60], 'target'] = 'tumor'
df.loc[df.index[60:], 'target'] = 'normal'

In [42]:
df[:108]

,Unnamed: 0,1007_s_at,1053_at,117_at,121_at,1255_g_at,1294_at,1316_at,1320_at,1405_i_at,...,AFFX-r2-Hs28SrRNA-M_at,AFFX-r2-P1-cre-3_at,AFFX-r2-P1-cre-5_at,AFFX-ThrX-3_at,AFFX-ThrX-5_at,AFFX-ThrX-M_at,AFFX-TrpnX-3_at,AFFX-TrpnX-5_at,AFFX-TrpnX-M_at,target
0,IDENTIFIER,MIR4640,RFC2,HSPA6,PAX8,GUCA1A,MIR5193,THRA,PTPN21,CCL5,...,--Control,--Control,--Control,--Control,--Control,--Control,--Control,--Control,--Control,NaN
1,GSM254629,10.9885,6.82603,7.77559,9.85506,4.82396,9.1043,6.19335,6.11913,7.7529,...,5.4294,12.6988,13.0276,5.4709,5.1512,4.58001,4.06666,4.63296,4.63396,tumor
2,GSM254648,10.6919,6.9096,7.68374,10.1321,4.98489,8.99562,6.31397,6.02121,8.14121,...,7.64748,13.219,13.3432,5.49011,5.28124,4.68364,4.04274,4.67585,4.5234,tumor
3,GSM254694,10.8978,6.80295,7.88498,9.8411,4.87689,9.26155,6.2566,6.07582,7.44056,...,5.93094,12.9839,12.9199,5.44948,5.30015,4.60809,4.11669,4.76781,4.55376,tumor
4,GSM254701,11.7494,6.81802,7.9384,9.90026,4.70904,9.68563,6.1893,6.00636,7.86048,...,5.87969,13.3904,13.351,5.39581,5.34466,4.68117,4.133,4.82604,4.73988,tumor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,GSM254710,10.3399,6.91376,8.28737,9.70648,4.88611,9.13011,6.0123,6.0088,8.64576,...,5.32332,12.6417,13.0444,5.32535,5.12411,4.48127,4.04516,4.66209,4.47608,normal
104,GSM254725,10.1936,7.00858,8.14476,10.107,4.94876,9.30555,6.44827,6.05265,8.66743,...,6.10278,12.7277,12.7103,5.35527,5.229,4.6619,4.00528,4.66702,4.85575,normal
105,GSM254651,10.2181,6.71859,9.0596,9.86705,4.95341,9.11727,6.24238,6.41734,7.78426,...,5.72003,12.9715,13.2777,5.33481,5.13456,4.46681,4.06027,4.7985,4.55662,normal
106,GSM254638,10.5767,6.62177,7.71877,10.0931,5.05479,9.00076,6.49048,6.05866,8.59067,...,5.74204,12.8623,13.028,5.59486,5.39204,4.71846,4.08097,4.6859,4.64581,normal
107,GSM254685,10.1841,6.62687,7.79599,9.70015,4.91616,8.87875,6.11221,6.24525,8.4876,...,6.02145,12.9833,12.9251,5.47283,5.34016,4.65254,4.0183,4.80305,4.73617,normal

In [ ]:
df = df.drop(0)
df[]

,Unnamed: 0,1007_s_at,1053_at,117_at,121_at,1255_g_at,1294_at,1316_at,1320_at,1405_i_at,...,AFFX-r2-Hs28SrRNA-M_at,AFFX-r2-P1-cre-3_at,AFFX-r2-P1-cre-5_at,AFFX-ThrX-3_at,AFFX-ThrX-5_at,AFFX-ThrX-M_at,AFFX-TrpnX-3_at,AFFX-TrpnX-5_at,AFFX-TrpnX-M_at,target
1,GSM254629,10.9885,6.82603,7.77559,9.85506,4.82396,9.1043,6.19335,6.11913,7.7529,...,5.4294,12.6988,13.0276,5.4709,5.1512,4.58001,4.06666,4.63296,4.63396,tumor
2,GSM254648,10.6919,6.9096,7.68374,10.1321,4.98489,8.99562,6.31397,6.02121,8.14121,...,7.64748,13.219,13.3432,5.49011,5.28124,4.68364,4.04274,4.67585,4.5234,tumor
3,GSM254694,10.8978,6.80295,7.88498,9.8411,4.87689,9.26155,6.2566,6.07582,7.44056,...,5.93094,12.9839,12.9199,5.44948,5.30015,4.60809,4.11669,4.76781,4.55376,tumor
4,GSM254701,11.7494,6.81802,7.9384,9.90026,4.70904,9.68563,6.1893,6.00636,7.86048,...,5.87969,13.3904,13.351,5.39581,5.34466,4.68117,4.133,4.82604,4.73988,tumor
5,GSM254728,10.9028,6.83816,8.01043,9.87185,4.78877,9.03172,6.30964,6.01719,8.23439,...,5.71502,12.8339,12.8981,5.2557,5.07107,4.46944,4.09605,4.62491,4.62771,tumor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,GO:Process,branching involved in mammary gland duct morph...,"DNA damage response, detection of DNA damage//...",NOT cellular heat acclimation///cellular respo...,anatomical structure morphogenesis///branching...,cellular response to calcium ion///phototransd...,ISG15-protein conjugation///cellular protein m...,Type I pneumocyte differentiation///adrenal gl...,peptidyl-tyrosine dephosphorylation///protein ...,G-protein coupled receptor signaling pathway//...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal
124,GO:Component,basolateral plasma membrane///extracellular ex...,Ctf18 RFC-like complex///DNA replication facto...,colocalizes_with COP9 signalosome///blood micr...,nucleoplasm///nucleoplasm///nucleus,photoreceptor disc membrane///photoreceptor in...,cytosol///cytosol///nucleoplasm///nucleus,cytosol///mitochondrion///nucleoplasm///nucleus,cytoplasm///cytoskeleton,cytoplasm///extracellular region///extracellul...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal
125,GO:Function ID,GO:0005524///GO:0005518///GO:0005518///GO:0046...,GO:0005524///contributes_to GO:0003689///GO:00...,GO:0005524///GO:0042623///GO:0019899///GO:0031...,GO:0003677///GO:0003677///GO:0000978///GO:0000...,GO:0005509///GO:0008048///GO:0030249,GO:0005524///GO:0019782///GO:0005515///GO:0004...,GO:0017025///GO:0031490///GO:0044213///GO:0005...,GO:0005515///GO:0004725,GO:0031726///GO:0031726///GO:0031726///GO:0031...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal
126,GO:Process ID,GO:0060444///GO:0007155///GO:0038063///GO:0038...,GO:0042769///GO:0006260///GO:0070987///GO:0042...,NOT GO:0070370///GO:0034605///GO:0034605///GO:...,GO:0009653///GO:0001658///GO:0071371///GO:0007...,GO:0071277///GO:0007602///GO:0031284///GO:0022...,GO:0032020///GO:0006464///GO:0019941///GO:0032...,GO:0060509///GO:0030325///GO:0007420///GO:0001...,GO:0035335///GO:0006470,GO:0007186///GO:0000165///GO:0031584///GO:0007...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal
127,GO:Component ID,GO:0016323///GO:0070062///GO:0005615///GO:0005...,GO:0031390///GO:0005663///GO:0005654,colocalizes_with GO:0008180///GO:0072562///GO:...,GO:0005654///GO:0005654///GO:0005634,GO:0097381///GO:0001917///GO:0005886,GO:0005829///GO:0005829///GO:0005654///GO:0005634,GO:0005829///GO:0005739///GO:0005654///GO:0005634,GO:0005737///GO:0005856,GO:0005737///GO:0005576///GO:0005615,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal

In [45]:
df[:107]

,Unnamed: 0,1007_s_at,1053_at,117_at,121_at,1255_g_at,1294_at,1316_at,1320_at,1405_i_at,...,AFFX-r2-Hs28SrRNA-M_at,AFFX-r2-P1-cre-3_at,AFFX-r2-P1-cre-5_at,AFFX-ThrX-3_at,AFFX-ThrX-5_at,AFFX-ThrX-M_at,AFFX-TrpnX-3_at,AFFX-TrpnX-5_at,AFFX-TrpnX-M_at,target
1,GSM254629,10.9885,6.82603,7.77559,9.85506,4.82396,9.1043,6.19335,6.11913,7.7529,...,5.4294,12.6988,13.0276,5.4709,5.1512,4.58001,4.06666,4.63296,4.63396,tumor
2,GSM254648,10.6919,6.9096,7.68374,10.1321,4.98489,8.99562,6.31397,6.02121,8.14121,...,7.64748,13.219,13.3432,5.49011,5.28124,4.68364,4.04274,4.67585,4.5234,tumor
3,GSM254694,10.8978,6.80295,7.88498,9.8411,4.87689,9.26155,6.2566,6.07582,7.44056,...,5.93094,12.9839,12.9199,5.44948,5.30015,4.60809,4.11669,4.76781,4.55376,tumor
4,GSM254701,11.7494,6.81802,7.9384,9.90026,4.70904,9.68563,6.1893,6.00636,7.86048,...,5.87969,13.3904,13.351,5.39581,5.34466,4.68117,4.133,4.82604,4.73988,tumor
5,GSM254728,10.9028,6.83816,8.01043,9.87185,4.78877,9.03172,6.30964,6.01719,8.23439,...,5.71502,12.8339,12.8981,5.2557,5.07107,4.46944,4.09605,4.62491,4.62771,tumor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,GSM254710,10.3399,6.91376,8.28737,9.70648,4.88611,9.13011,6.0123,6.0088,8.64576,...,5.32332,12.6417,13.0444,5.32535,5.12411,4.48127,4.04516,4.66209,4.47608,normal
104,GSM254725,10.1936,7.00858,8.14476,10.107,4.94876,9.30555,6.44827,6.05265,8.66743,...,6.10278,12.7277,12.7103,5.35527,5.229,4.6619,4.00528,4.66702,4.85575,normal
105,GSM254651,10.2181,6.71859,9.0596,9.86705,4.95341,9.11727,6.24238,6.41734,7.78426,...,5.72003,12.9715,13.2777,5.33481,5.13456,4.46681,4.06027,4.7985,4.55662,normal
106,GSM254638,10.5767,6.62177,7.71877,10.0931,5.05479,9.00076,6.49048,6.05866,8.59067,...,5.74204,12.8623,13.028,5.59486,5.39204,4.71846,4.08097,4.6859,4.64581,normal
107,GSM254685,10.1841,6.62687,7.79599,9.70015,4.91616,8.87875,6.11221,6.24525,8.4876,...,6.02145,12.9833,12.9251,5.47283,5.34016,4.65254,4.0183,4.80305,4.73617,normal

In [46]:
new_df = df.loc[:107]

In [48]:
new_df[:109]

,Unnamed: 0,1007_s_at,1053_at,117_at,121_at,1255_g_at,1294_at,1316_at,1320_at,1405_i_at,...,AFFX-r2-Hs28SrRNA-M_at,AFFX-r2-P1-cre-3_at,AFFX-r2-P1-cre-5_at,AFFX-ThrX-3_at,AFFX-ThrX-5_at,AFFX-ThrX-M_at,AFFX-TrpnX-3_at,AFFX-TrpnX-5_at,AFFX-TrpnX-M_at,target
1,GSM254629,10.9885,6.82603,7.77559,9.85506,4.82396,9.1043,6.19335,6.11913,7.7529,...,5.4294,12.6988,13.0276,5.4709,5.1512,4.58001,4.06666,4.63296,4.63396,tumor
2,GSM254648,10.6919,6.9096,7.68374,10.1321,4.98489,8.99562,6.31397,6.02121,8.14121,...,7.64748,13.219,13.3432,5.49011,5.28124,4.68364,4.04274,4.67585,4.5234,tumor
3,GSM254694,10.8978,6.80295,7.88498,9.8411,4.87689,9.26155,6.2566,6.07582,7.44056,...,5.93094,12.9839,12.9199,5.44948,5.30015,4.60809,4.11669,4.76781,4.55376,tumor
4,GSM254701,11.7494,6.81802,7.9384,9.90026,4.70904,9.68563,6.1893,6.00636,7.86048,...,5.87969,13.3904,13.351,5.39581,5.34466,4.68117,4.133,4.82604,4.73988,tumor
5,GSM254728,10.9028,6.83816,8.01043,9.87185,4.78877,9.03172,6.30964,6.01719,8.23439,...,5.71502,12.8339,12.8981,5.2557,5.07107,4.46944,4.09605,4.62491,4.62771,tumor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,GSM254710,10.3399,6.91376,8.28737,9.70648,4.88611,9.13011,6.0123,6.0088,8.64576,...,5.32332,12.6417,13.0444,5.32535,5.12411,4.48127,4.04516,4.66209,4.47608,normal
104,GSM254725,10.1936,7.00858,8.14476,10.107,4.94876,9.30555,6.44827,6.05265,8.66743,...,6.10278,12.7277,12.7103,5.35527,5.229,4.6619,4.00528,4.66702,4.85575,normal
105,GSM254651,10.2181,6.71859,9.0596,9.86705,4.95341,9.11727,6.24238,6.41734,7.78426,...,5.72003,12.9715,13.2777,5.33481,5.13456,4.46681,4.06027,4.7985,4.55662,normal
106,GSM254638,10.5767,6.62177,7.71877,10.0931,5.05479,9.00076,6.49048,6.05866,8.59067,...,5.74204,12.8623,13.028,5.59486,5.39204,4.71846,4.08097,4.6859,4.64581,normal
107,GSM254685,10.1841,6.62687,7.79599,9.70015,4.91616,8.87875,6.11221,6.24525,8.4876,...,6.02145,12.9833,12.9251,5.47283,5.34016,4.65254,4.0183,4.80305,4.73617,normal

In [47]:
new_df.to_csv('transposed_GDS3257_add_target.csv', index=False)

In [2]:
import pandas as pd
df = pd.read_csv(r'C:\Users\User\Documents\GitHub\AIforBioinformatics\dataset\transposed_GDS3257_add_target.csv')

In [5]:
df[df['target'] == 'tumor'].count()

Unnamed: 0         59
1007_s_at          59
1053_at            59
117_at             59
121_at             59
                   ..
AFFX-ThrX-M_at     59
AFFX-TrpnX-3_at    59
AFFX-TrpnX-5_at    59
AFFX-TrpnX-M_at    59
target             59
Length: 22285, dtype: int64

In [6]:
df[df['target'] == 'normal'].count()

Unnamed: 0         48
1007_s_at          48
1053_at            48
117_at             48
121_at             48
                   ..
AFFX-ThrX-M_at     48
AFFX-TrpnX-3_at    48
AFFX-TrpnX-5_at    48
AFFX-TrpnX-M_at    48
target             48
Length: 22285, dtype: int64

In [4]:
import pandas as pd
df_identifier = pd.read_csv(r'C:\Users\User\Documents\GitHub\AIforBioinformatics\ignore_dir\dataset\transposed_GDS3257.csv')
df_identifier

C:\Users\User\AppData\Local\Temp\ipykernel_7560\645506907.py:2: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074,1075,1076,1077,1078,1079,1080,1081,1082,1083,1084,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094,1095,1096,1097,1098,1099,1100,1101,1102,1103,1104,1105,1106,1107,1108,1109,1110,1111,1112,1113,1114,1115,1116,1117,1118,1119,1120,1121,1122,1123,1124,1125,1126,1127,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1141,1142,1143,1144,1145,1146,1147,1148,1149,1150,1151,1152,1153,1154,1155,1156,1157,1158,1159,1160,1161,1162,1163,1164,1165,1166,1167,1168,1169,1170,1171,1172,1173,1174,1175,1176,1177,1178,1179,1180,1181,1182,1183,1184,1185,1186,1187,1188,1189,1190,1191,1192,1193,1194,1195,1196,1197,1198,1199,1200,1201,1202,1203,1204,1205,1206,1207,1208,1209,1210,1211,1212,1213,1214,1215,1216,1217,1218,1219,1220,1221,1222,1223,1224,1225,1226,1227,1228,1229,1230,1231,1232,1233,1234,1235,1236,1237,1238,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1252,1253,1254,1255,1256,1257,1258,1259,1260,1261,1262,1263,1264,1265,1266,1267,1268,1269,1270,1271,1272,1273,1274,1275,1276,1277,1278,1279,1280,1281,1282,1283,1284,1285,1286,1287,1288,1289,1290,1291,1292,1293,1294,1295,1296,1297,1298,1299,1300,1301,1302,1303,1304,1305,1306,1307,1308,1309,1310,1311,1312,1313,1314,1315,1316,1317,1318,1319,1320,1321,1322,1323,1324,1325,1326,1327,1328,1329,1330,1331,1332,1333,1334,1335,1336,1337,1338,1339,1340,1341,1342,1343,1344,1345,1346,1347,1348,1349,1350,1351,1352,1353,1354,1355,1356,1357,1358,1359,1360,1361,1362,1363,1364,1365,1366,1367,1368,1369,1370,1371,1372,1373,1374,1375,1376,1377,1378,1379,1380,1381,1382,1383,1384,1385,1386,1387,1388,1389,1390,1391,1392,1393,1394,1395,1396,1397,1398,1399,1400,1401,1402,1403,1404,1405,1406,1407,1408,1409,1410,1411,1412,1413,1414,1415,1416,1417,1418,1419,1420,1421,1422,1423,1424,1425,1426,1427,1428,1429,1430,1431,1432,1433,1434,1435,1436,1437,1438,1439,1440,1441,1442,1443,1444,1445,1446,1447,1448,1449,1450,1451,1452,1453,1454,1455,1456,1457,1458,1459,1460,1461,1462,1463,1464,1465,1466,1467,1468,1469,1470,1471,1472,1473,1474,1475,1476,1477,1478,1479,1480,1481,1482,1483,1484,1485,1486,1487,1488,1489,1490,1491,1492,1493,1494,1495,1496,1497,1498,1499,1500,1501,1502,1503,1504,1505,1506,1507,1508,1509,1510,1511,1512,1513,1514,1515,1516,1517,1518,1519,1520,1521,1522,1523,1524,1525,1526,1527,1528,1529,1530,1531,1532,1533,1534,1535,1536,1537,1538,1539,1540,1541,1542,1543,1544,1545,1546,1547,1548,1549,1550,1551,1552,1553,1554,1555,1556,1557,1558,1559,1560,1561,1562,1563,1564,1565,1566,1567,1568,1569,1570,1571,1572,1573,1574,1575,1576,1577,1578,1579,1580,1581,1582,1583,1584,1585,1586,1587,1588,1589,1590,1591,1592,1593,1594,1595,1596,1597,1598,1599,1600,1601,1602,1603,1604,1605,1606,1607,1608,1609,1610,1611,1612,1613,1614,1615,1616,1617,1618,1619,1620,1621,1622,1623,1624,1625,1626,1627,1628,1629,1630,1631,1632,1633,1634,1635,1636,1637,1638,1639,1640,1641,1642,1643,1644,1645,1646,1647,1648,1649,1650,1651,1652,1653,1654,1655,1656,1657,1658,1659,1660,1661,1662,1663,1664,1665,1666,1667,1668,1669,1670,1671,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682,1683,1684,1685,1686,1687,1688,1689,1690,1691,1692,1693,1694,1695,1696,1697,1698,1699,1700,1701,1702,1703,1704,1705,1706,1707,1708,1709,1710,1711,1712,1713,1714,1715,1716,1717,1718,1719,1720,1721,1722,1723,1724,1725,1726,1727,1728,1729,1730,1731,1732,1733,1734,1735,1736,1737,1738,1739,1740,1741,1742,1743,1744,1745,1746,1747,1748,1749,1750,1751,1752,1753,1754,1755,1756,1757,1758,1759,1760,1761,1762,1763,1764,1765,1766,1767,1768,1769,1770,1771,1772,1773,1774,1775,1776,1777,1778,1779,1780,1781,1782,1783,1784,1785,1786,1787,1788,1789,1790,1791,1792,1793,1794,1795,1796,1797,1798,1799,1800,1801,1802,1803,1804,1805,1806,1807,1808,1809,1810,1811,1812,1813,1814,1815,1816,1817,1818,1819,1820,1821,1822,1823,1824,1825,1826,1827,1828,1829,1830,1831,1832,1833,1834,1835,1836,1837,1838,1839,1840,1841,1842,1843,1844,1845,1846,1847,1848,1849,1850,1851,1852,1853,1854,1855,1856,1857,1858,1859,1860,1861,1862,1863,1864,1865,1866,1867,1868,1869,1870,1871,1872,1873,1874,1875,1876,1877,1878,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1899,1900,1901,1902,1903,1904,1905,1906,1907,1908,1909,1910,1911,1912,1913,1914,1915,1916,1917,1918,1919,1920,1921,1922,1923,1924,1925,1926,1927,1928,1929,1930,1931,1932,1933,1934,1935,1936,1937,1938,1939,1940,1941,1942,1943,1944,1945,1946,1947,1948,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035,2036,2037,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047,2048,2049,2050,2051,2052,2053,2054,2055,2056,2057,2058,2059,2060,2061,2062,2063,2064,2065,2066,2067,2068,2069,2070,2071,2072,2073,2074,2075,2076,2077,2078,2079,2080,2081,2082,2083,2084,2085,2086,2087,2088,2089,2090,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100,2101,2102,2103,2104,2105,2106,2107,2108,2109,2110,2111,2112,2113,2114,2115,2116,2117,2118,2119,2120,2121,2122,2123,2124,2125,2126,2127,2128,2129,2130,2131,2132,2133,2134,2135,2136,2137,2138,2139,2140,2141,2142,2143,2144,2145,2146,2147,2148,2149,2150,2151,2152,2153,2154,2155,2156,2157,2158,2159,2160,2161,2162,2163,2164,2165,2166,2167,2168,2169,2170,2171,2172,2173,2174,2175,2176,2177,2178,2179,2180,2181,2182,2183,2184,2185,2186,2187,2188,2189,2190,2191,2192,2193,2194,2195,2196,2197,2198,2199,2200,2201,2202,2203,2204,2205,2206,2207,2208,2209,2210,2211,2212,2213,2214,2215,2216,2217,2218,2219,2220,2221,2222,2223,2224,2225,2226,2227,2228,2229,2230,2231,2232,2233,2234,2235,2236,2237,2238,2239,2240,2241,2242,2243,2244,2245,2246,2247,2248,2249,2250,2251,2252,2253,2254,2255,2256,2257,2258,2259,2260,2261,2262,2263,2264,2265,2266,2267,2268,2269,2270,2271,2272,2273,2274,2275,2276,2277,2278,2279,2280,2281,2282,2283,2284,2285,2286,2287,2288,2289,2290,2291,2292,2293,2294,2295,2296,2297,2298,2299,2300,2301,2302,2303,2304,2305,2306,2307,2308,2309,2310,2311,2312,2313,2314,2315,2316,2317,2318,2319,2320,2321,2322,2323,2324,2325,2326,2327,2328,2329,2330,2331,2332,2333,2334,2335,2336,2337,2338,2339,2340,2341,2342,2343,2344,2345,2346,2347,2348,2349,2350,2351,2352,2353,2354,2355,2356,2357,2358,2359,2360,2361,2362,2363,2364,2365,2366,2367,2368,2369,2370,2371,2372,2373,2374,2375,2376,2377,2378,2379,2380,2381,2382,2383,2384,2385,2386,2387,2388,2389,2390,2391,2392,2393,2394,2395,2396,2397,2398,2399,2400,2401,2402,2403,2404,2405,2406,2407,2408,2409,2410,2411,2412,2413,2414,2415,2416,2417,2418,2419,2420,2421,2422,2423,2424,2425,2426,2427,2428,2429,2430,2431,2432,2433,2434,2435,2436,2437,2438,2439,2440,2441,2442,2443,2444,2445,2446,2447,2448,2449,2450,2451,2452,2453,2454,2455,2456,2457,2458,2459,2460,2461,2462,2463,2464,2465,2466,2467,2468,2469,2470,2471,2472,2473,2474,2475,2476,2477,2478,2479,2480,2481,2482,2483,2484,2485,2486,2487,2488,2489,2490,2491,2492,2493,2494,2495,2496,2497,2498,2499,2500,2501,2502,2503,2504,2505,2506,2507,2508,2509,2510,2511,2512,2513,2514,2515,2516,2517,2518,2519,2520,2521,2522,2523,2524,2525,2526,2527,2528,2529,2530,2531,2532,2533,2534,2535,2536,2537,2538,2539,2540,2541,2542,2543,2544,2545,2546,2547,2548,2549,2550,2551,2552,2553,2554,2555,2556,2557,2558,2559,2560,2561,2562,2563,2564,2565,2566,2567,2568,2569,2570,2571,2572,2573,2574,2575,2576,2577,2578,2579,2580,2581,2582,2583,2584,2585,2586,2587,2588,2589,2590,2591,2592,2593,2594,2595,2596,2597,2598,2599,2600,2601,2602,2603,2604,2605,2606,2607,2608,2609,2610,2611,2612,2613,2614,2615,2616,2617,2618,2619,2620,2621,2622,2623,2624,2625,2626,2627,2628,2629,2630,2631,2632,2633,2634,2635,2636,2637,2638,2639,2640,2641,2642,2643,2644,2645,2646,2647,2648,2649,2650,2651,2652,2653,2654,2655,2656,2657,2658,2659,2660,2661,2662,2663,2664,2665,2666,2667,2668,2669,2670,2671,2672,2673,2674,2675,2676,2677,2678,2679,2680,2681,2682,2683,2684,2685,2686,2687,2688,2689,2690,2691,2692,2693,2694,2695,2696,2697,2698,2699,2700,2701,2702,2703,2704,2705,2706,2707,2708,2709,2710,2711,2712,2713,2714,2715,2716,2717,2718,2719,2720,2721,2722,2723,2724,2725,2726,2727,2728,2729,2730,2731,2732,2733,2734,2735,2736,2737,2738,2739,2740,2741,2742,2743,2744,2745,2746,2747,2748,2749,2750,2751,2752,2753,2754,2755,2756,2757,2758,2759,2760,2761,2762,2763,2764,2765,2766,2767,2768,2769,2770,2771,2772,2773,2774,2775,2776,2777,2778,2779,2780,2781,2782,2783,2784,2785,2786,2787,2788,2789,2790,2791,2792,2793,2794,2795,2796,2797,2798,2799,2800,2801,2802,2803,2804,2805,2806,2807,2808,2809,2810,2811,2812,2813,2814,2815,2816,2817,2818,2819,2820,2821,2822,2823,2824,2825,2826,2827,2828,2829,2830,2831,2832,2833,2834,2835,2836,2837,2838,2839,2840,2841,2842,2843,2844,2845,2846,2847,2848,2849,2850,2851,2852,2853,2854,2855,2856,2857,2858,2859,2860,2861,2862,2863,2864,2865,2866,2867,2868,2869,2870,2871,2872,2873,2874,2875,2876,2877,2878,2879,2880,2881,2882,2883,2884,2885,2886,2887,2888,2889,2890,2891,2892,2893,2894,2895,2896,2897,2898,2899,2900,2901,2902,2903,2904,2905,2906,2907,2908,2909,2910,2911,2912,2913,2914,2915,2916,2917,2918,2919,2920,2921,2922,2923,2924,2925,2926,2927,2928,2929,2930,2931,2932,2933,2934,2935,2936,2937,2938,2939,2940,2941,2942,2943,2944,2945,2946,2947,2948,2949,2950,2951,2952,2953,2954,2955,2956,2957,2958,2959,2960,2961,2962,2963,2964,2965,2966,2967,2968,2969,2970,2971,2972,2973,2974,2975,2976,2977,2978,2979,2980,2981,2982,2983,2984,2985,2986,2987,2988,2989,2990,2991,2992,2993,2994,2995,2996,2997,2998,2999,3000,3001,3002,3003,3004,3005,3006,3007,3008,3009,3010,3011,3012,3013,3014,3015,3016,3017,3018,3019,3020,3021,3022,3023,3024,3025,3026,3027,3028,3029,3030,3031,3032,3033,3034,3035,3036,3037,3038,3039,3040,3041,3042,3043,3044,3045,3046,3047,3048,3049,3050,3051,3052,3053,3054,3055,3056,3057,3058,3059,3060,3061,3062,3063,3064,3065,3066,3067,3068,3069,3070,3071,3072,3073,3074,3075,3076,3077,3078,3079,3080,3081,3082,3083,3084,3085,3086,3087,3088,3089,3090,3091,3092,3093,3094,3095,3096,3097,3098,3099,3100,3101,3102,3103,3104,3105,3106,3107,3108,3109,3110,3111,3112,3113,3114,3115,3116,3117,3118,3119,3120,3121,3122,3123,3124,3125,3126,3127,3128,3129,3130,3131,3132,3133,3134,3135,3136,3137,3138,3139,3140,3141,3142,3143,3144,3145,3146,3147,3148,3149,3150,3151,3152,3153,3154,3155,3156,3157,3158,3159,3160,3161,3162,3163,3164,3165,3166,3167,3168,3169,3170,3171,3172,3173,3174,3175,3176,3177,3178,3179,3180,3181,3182,3183,3184,3185,3186,3187,3188,3189,3190,3191,3192,3193,3194,3195,3196,3197,3198,3199,3200,3201,3202,3203,3204,3205,3206,3207,3208,3209,3210,3211,3212,3213,3214,3215,3216,3217,3218,3219,3220,3221,3222,3223,3224,3225,3226,3227,3228,3229,3230,3231,3232,3233,3234,3235,3236,3237,3238,3239,3240,3241,3242,3243,3244,3245,3246,3247,3248,3249,3250,3251,3252,3253,3254,3255,3256,3257,3258,3259,3260,3261,3262,3263,3264,3265,3266,3267,3268,3269,3270,3271,3272,3273,3274,3275,3276,3277,3278,3279,3280,3281,3282,3283,3284,3285,3286,3287,3288,3289,3290,3291,3292,3293,3294,3295,3296,3297,3298,3299,3300,3301,3302,3303,3304,3305,3306,3307,3308,3309,3310,3311,3312,3313,3314,3315,3316,3317,3318,3319,3320,3321,3322,3323,3324,3325,3326,3327,3328,3329,3330,3331,3332,3333,3334,3335,3336,3337,3338,3339,3340,3341,3342,3343,3344,3345,3346,3347,3348,3349,3350,3351,3352,3353,3354,3355,3356,3357,3358,3359,3360,3361,3362,3363,3364,3365,3366,3367,3368,3369,3370,3371,3372,3373,3374,3375,3376,3377,3378,3379,3380,3381,3382,3383,3384,3385,3386,3387,3388,3389,3390,3391,3392,3393,3394,3395,3396,3397,3398,3399,3400,3401,3402,3403,3404,3405,3406,3407,3408,3409,3410,3411,3412,3413,3414,3415,3416,3417,3418,3419,3420,3421,3422,3423,3424,3425,3426,3427,3428,3429,3430,3431,3432,3433,3434,3435,3436,3437,3438,3439,3440,3441,3442,3443,3444,3445,3446,3447,3448,3449,3450,3451,3452,3453,3454,3455,3456,3457,3458,3459,3460,3461,3462,3463,3464,3465,3466,3467,3468,3469,3470,3471,3472,3473,3474,3475,3476,3477,3478,3479,3480,3481,3482,3483,3484,3485,3486,3487,3488,3489,3490,3491,3492,3493,3494,3495,3496,3497,3498,3499,3500,3501,3502,3503,3504,3505,3506,3507,3508,3509,3510,3511,3512,3513,3514,3515,3516,3517,3518,3519,3520,3521,3522,3523,3524,3525,3526,3527,3528,3529,3530,3531,3532,3533,3534,3535,3536,3537,3538,3539,3540,3541,3542,3543,3544,3545,3546,3547,3548,3549,3550,3551,3552,3553,3554,3555,3556,3557,3558,3559,3560,3561,3562,3563,3564,3565,3566,3567,3568,3569,3570,3571,3572,3573,3574,3575,3576,3577,3578,3579,3580,3581,3582,3583,3584,3585,3586,3587,3588,3589,3590,3591,3592,3593,3594,3595,3596,3597,3598,3599,3600,3601,3602,3603,3604,3605,3606,3607,3608,3609,3610,3611,3612,3613,3614,3615,3616,3617,3618,3619,3620,3621,3622,3623,3624,3625,3626,3627,3628,3629,3630,3631,3632,3633,3634,3635,3636,3637,3638,3639,3640,3641,3642,3643,3644,3645,3646,3647,3648,3649,3650,3651,3652,3653,3654,3655,3656,3657,3658,3659,3660,3661,3662,3663,3664,3665,3666,3667,3668,3669,3670,3671,3672,3673,3674,3675,3676,3677,3678,3679,3680,3681,3682,3683,3684,3685,3686,3687,3688,3689,3690,3691,3692,3693,3694,3695,3696,3697,3698,3699,3700,3701,3702,3703,3704,3705,3706,3707,3708,3709,3710,3711,3712,3713,3714,3715,3716,3717,3718,3719,3720,3721,3722,3723,3724,3725,3726,3727,3728,3729,3730,3731,3732,3733,3734,3735,3736,3737,3738,3739,3740,3741,3742,3743,3744,3745,3746,3747,3748,3749,3750,3751,3752,3753,3754,3755,3756,3757,3758,3759,3760,3761,3762,3763,3764,3765,3766,3767,3768,3769,3770,3771,3772,3773,3774,3775,3776,3777,3778,3779,3780,3781,3782,3783,3784,3785,3786,3787,3788,3789,3790,3791,3792,3793,3794,3795,3796,3797,3798,3799,3800,3801,3802,3803,3804,3805,3806,3807,3808,3809,3810,3811,3812,3813,3814,3815,3816,3817,3818,3819,3820,3821,3822,3823,3824,3825,3826,3827,3828,3829,3830,3831,3832,3833,3834,3835,3836,3837,3838,3839,3840,3841,3842,3843,3844,3845,3846,3847,3848,3849,3850,3851,3852,3853,3854,3855,3856,3857,3858,3859,3860,3861,3862,3863,3864,3865,3866,3867,3868,3869,3870,3871,3872,3873,3874,3875,3876,3877,3878,3879,3880,3881,3882,3883,3884,3885,3886,3887,3888,3889,3890,3891,3892,3893,3894,3895,3896,3897,3898,3899,3900,3901,3902,3903,3904,3905,3906,3907,3908,3909,3910,3911,3912,3913,3914,3915,3916,3917,3918,3919,3920,3921,3922,3923,3924,3925,3926,3927,3928,3929,3930,3931,3932,3933,3934,3935,3936,3937,3938,3939,3940,3941,3942,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952,3953,3954,3955,3956,3957,3958,3959,3960,3961,3962,3963,3964,3965,3966,3967,3968,3969,3970,3971,3972,3973,3974,3975,3976,3977,3978,3979,3980,3981,3982,3983,3984,3985,3986,3987,3988,3989,3990,3991,3992,3993,3994,3995,3996,3997,3998,3999,4000,4001,4002,4003,4004,4005,4006,4007,4008,4009,4010,4011,4012,4013,4014,4015,4016,4017,4018,4019,4020,4021,4022,4023,4024,4025,4026,4027,4028,4029,4030,4031,4032,4033,4034,4035,4036,4037,4038,4039,4040,4041,4042,4043,4044,4045,4046,4047,4048,4049,4050,4051,4052,4053,4054,4055,4056,4057,4058,4059,4060,4061,4062,4063,4064,4065,4066,4067,4068,4069,4070,4071,4072,4073,4074,4075,4076,4077,4078,4079,4080,4081,4082,4083,4084,4085,4086,4087,4088,4089,4090,4091,4092,4093,4094,4095,4096,4097,4098,4099,4100,4101,4102,4103,4104,4105,4106,4107,4108,4109,4110,4111,4112,4113,4114,4115,4116,4117,4118,4119,4120,4121,4122,4123,4124,4125,4126,4127,4128,4129,4130,4131,4132,4133,4134,4135,4136,4137,4138,4139,4140,4141,4142,4143,4144,4145,4146,4147,4148,4149,4150,4151,4152,4153,4154,4155,4156,4157,4158,4159,4160,4161,4162,4163,4164,4165,4166,4167,4168,4169,4170,4171,4172,4173,4174,4175,4176,4177,4178,4179,4180,4181,4182,4183,4184,4185,4186,4187,4188,4189,4190,4191,4192,4193,4194,4195,4196,4197,4198,4199,4200,4201,4202,4203,4204,

,Unnamed: 0,1007_s_at,1053_at,117_at,121_at,1255_g_at,1294_at,1316_at,1320_at,1405_i_at,...,AFFX-r2-Hs28SrRNA-5_at,AFFX-r2-Hs28SrRNA-M_at,AFFX-r2-P1-cre-3_at,AFFX-r2-P1-cre-5_at,AFFX-ThrX-3_at,AFFX-ThrX-5_at,AFFX-ThrX-M_at,AFFX-TrpnX-3_at,AFFX-TrpnX-5_at,AFFX-TrpnX-M_at
0,IDENTIFIER,MIR4640,RFC2,HSPA6,PAX8,GUCA1A,MIR5193,THRA,PTPN21,CCL5,...,--Control,--Control,--Control,--Control,--Control,--Control,--Control,--Control,--Control,--Control
1,GSM254629,10.9885,6.82603,7.77559,9.85506,4.82396,9.1043,6.19335,6.11913,7.7529,...,4.99415,5.4294,12.6988,13.0276,5.4709,5.1512,4.58001,4.06666,4.63296,4.63396
2,GSM254648,10.6919,6.9096,7.68374,10.1321,4.98489,8.99562,6.31397,6.02121,8.14121,...,6.15485,7.64748,13.219,13.3432,5.49011,5.28124,4.68364,4.04274,4.67585,4.5234
3,GSM254694,10.8978,6.80295,7.88498,9.8411,4.87689,9.26155,6.2566,6.07582,7.44056,...,5.21648,5.93094,12.9839,12.9199,5.44948,5.30015,4.60809,4.11669,4.76781,4.55376
4,GSM254701,11.7494,6.81802,7.9384,9.90026,4.70904,9.68563,6.1893,6.00636,7.86048,...,5.0627,5.87969,13.3904,13.351,5.39581,5.34466,4.68117,4.133,4.82604,4.73988
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,GO:Process,branching involved in mammary gland duct morph...,"DNA damage response, detection of DNA damage//...",NOT cellular heat acclimation///cellular respo...,anatomical structure morphogenesis///branching...,cellular response to calcium ion///phototransd...,ISG15-protein conjugation///cellular protein m...,Type I pneumocyte differentiation///adrenal gl...,peptidyl-tyrosine dephosphorylation///protein ...,G-protein coupled receptor signaling pathway//...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,GO:Component,basolateral plasma membrane///extracellular ex...,Ctf18 RFC-like complex///DNA replication facto...,colocalizes_with COP9 signalosome///blood micr...,nucleoplasm///nucleoplasm///nucleus,photoreceptor disc membrane///photoreceptor in...,cytosol///cytosol///nucleoplasm///nucleus,cytosol///mitochondrion///nucleoplasm///nucleus,cytoplasm///cytoskeleton,cytoplasm///extracellular region///extracellul...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,GO:Function ID,GO:0005524///GO:0005518///GO:0005518///GO:0046...,GO:0005524///contributes_to GO:0003689///GO:00...,GO:0005524///GO:0042623///GO:0019899///GO:0031...,GO:0003677///GO:0003677///GO:0000978///GO:0000...,GO:0005509///GO:0008048///GO:0030249,GO:0005524///GO:0019782///GO:0005515///GO:0004...,GO:0017025///GO:0031490///GO:0044213///GO:0005...,GO:0005515///GO:0004725,GO:0031726///GO:0031726///GO:0031726///GO:0031...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,GO:Process ID,GO:0060444///GO:0007155///GO:0038063///GO:0038...,GO:0042769///GO:0006260///GO:0070987///GO:0042...,NOT GO:0070370///GO:0034605///GO:0034605///GO:...,GO:0009653///GO:0001658///GO:0071371///GO:0007...,GO:0071277///GO:0007602///GO:0031284///GO:0022...,GO:0032020///GO:0006464///GO:0019941///GO:0032...,GO:0060509///GO:0030325///GO:0007420///GO:0001...,GO:0035335///GO:0006470,GO:0007186///GO:0000165///GO:0031584///GO:0007...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,GO:Component ID,GO:0016323///GO:0070062///GO:0005615///GO:0005...,GO:0031390///GO:0005663///GO:0005654,colocalizes_with GO:0008180///GO:0072562///GO:...,GO:0005654///GO:0005654///GO:0005634,GO:0097381///GO:0001917///GO:0005886,GO:0005829///GO:0005829///GO:0005654///GO:0005634,GO:0005829///GO:0005739///GO:0005654///GO:0005634,GO:0005737///GO:0005856,GO:0005737///GO:0005576///GO:0005615,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_target = pd.read_csv(r'C:\Users\User\Documents\GitHub\AIforBioinformatics\ignore_dir\dataset\transposed_GDS3257_add_target.csv')
df_target

,Unnamed: 0,1007_s_at,1053_at,117_at,121_at,1255_g_at,1294_at,1316_at,1320_at,1405_i_at,...,AFFX-r2-Hs28SrRNA-M_at,AFFX-r2-P1-cre-3_at,AFFX-r2-P1-cre-5_at,AFFX-ThrX-3_at,AFFX-ThrX-5_at,AFFX-ThrX-M_at,AFFX-TrpnX-3_at,AFFX-TrpnX-5_at,AFFX-TrpnX-M_at,target
0,GSM254629,10.9885,6.82603,7.77559,9.85506,4.82396,9.10430,6.19335,6.11913,7.75290,...,5.42940,12.6988,13.0276,5.47090,5.15120,4.58001,4.06666,4.63296,4.63396,tumor
1,GSM254648,10.6919,6.90960,7.68374,10.13210,4.98489,8.99562,6.31397,6.02121,8.14121,...,7.64748,13.2190,13.3432,5.49011,5.28124,4.68364,4.04274,4.67585,4.52340,tumor
2,GSM254694,10.8978,6.80295,7.88498,9.84110,4.87689,9.26155,6.25660,6.07582,7.44056,...,5.93094,12.9839,12.9199,5.44948,5.30015,4.60809,4.11669,4.76781,4.55376,tumor
3,GSM254701,11.7494,6.81802,7.93840,9.90026,4.70904,9.68563,6.18930,6.00636,7.86048,...,5.87969,13.3904,13.3510,5.39581,5.34466,4.68117,4.13300,4.82604,4.73988,tumor
4,GSM254728,10.9028,6.83816,8.01043,9.87185,4.78877,9.03172,6.30964,6.01719,8.23439,...,5.71502,12.8339,12.8981,5.25570,5.07107,4.46944,4.09605,4.62491,4.62771,tumor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,GSM254710,10.3399,6.91376,8.28737,9.70648,4.88611,9.13011,6.01230,6.00880,8.64576,...,5.32332,12.6417,13.0444,5.32535,5.12411,4.48127,4.04516,4.66209,4.47608,normal
103,GSM254725,10.1936,7.00858,8.14476,10.10700,4.94876,9.30555,6.44827,6.05265,8.66743,...,6.10278,12.7277,12.7103,5.35527,5.22900,4.66190,4.00528,4.66702,4.85575,normal
104,GSM254651,10.2181,6.71859,9.05960,9.86705,4.95341,9.11727,6.24238,6.41734,7.78426,...,5.72003,12.9715,13.2777,5.33481,5.13456,4.46681,4.06027,4.79850,4.55662,normal
105,GSM254638,10.5767,6.62177,7.71877,10.09310,5.05479,9.00076,6.49048,6.05866,8.59067,...,5.74204,12.8623,13.0280,5.59486,5.39204,4.71846,4.08097,4.68590,4.64581,normal
106,GSM254685,10.1841,6.62687,7.79599,9.70015,4.91616,8.87875,6.11221,6.24525,8.48760,...,6.02145,12.9833,12.9251,5.47283,5.34016,4.65254,4.01830,4.80305,4.73617,normal

In [27]:
m_tar = list(df_target)
tar_get = pd.DataFrame({'probe': m_tar})

In [28]:
tar_get = tar_get.drop(0)
tar_get

                 probe
1            1007_s_at
2              1053_at
3               117_at
4               121_at
5            1255_g_at
...                ...
22280   AFFX-ThrX-M_at
22281  AFFX-TrpnX-3_at
22282  AFFX-TrpnX-5_at
22283  AFFX-TrpnX-M_at
22284           target

[22284 rows x 1 columns]

In [ ]:
row_list = df_identifier.iloc[0].tolist()

print(row_list)
iden = pd.DataFrame({'IDENTIFIER': row_list})

['IDENTIFIER', 'MIR4640', 'RFC2', 'HSPA6', 'PAX8', 'GUCA1A', 'MIR5193', 'THRA', 'PTPN21', 'CCL5', 'CYP2E1', 'EPHB3', 'ESRRA', 'CYP2A6', 'GAS6', 'MMP14', 'TRADD', 'CHURC1-FNTB', 'PLD1', 'DTX2P1-UPK3BP1-PMS2P11', 'BAD', 'PRPF8', 'CAPNS1', 'RPL35', 'MIR6805', 'EIF4G2', 'EIF3D', 'PARK7', 'SRP14', 'GDI2', 'GDI2', 'RPL11', 'ARF3', 'RPL21P28', 'RPL24', 'HNRNPC', 'SEPT2', 'HNRNPA1P10', 'RPS27A', 'LOC100508408', 'FAU', 'TARDBP', 'CFL1', 'RPL18', 'EIF3F', 'RPS5', 'RPL27', 'RPL34', 'NARS', 'STARD7', 'RPL19', 'SLC25A3', 'SNORD35B', 'RPL9', 'MIR5047', 'RPL6', 'CTDNEP1', 'RPL10A', 'CBX3', 'RPL17-C18orf32', 'PSMB2', 'KHDRBS1', 'ATP6V1G2-DDX39B', 'RTCB', 'ERH', 'GATC', 'ABCF1', 'DAD1', 'YY1', 'JTB', 'KAT7', 'ZNF146', 'SART1', 'ILF2', 'SPAG7', 'ZPR1', 'TAF10', 'C1D', 'NONO', 'LOC101929240', 'RHOA', 'RNPS1', 'RPS24', 'RPL30', 'NPM1', 'HSP90AB1', 'MIR3620', 'IK', 'SNX3', 'CANX', 'SART3', 'CNPPD1', 'SMNDC1', 'HNRNPM', 'HNRNPD', 'RPL14', 'GUK1', 'KXD1', 'OAZ1', 'ATP6V0B', 'KARS', 'H3F3AP4', 'RPS6', 'RPS7', 'USP22', 'C11orf58', 'TCEB2', 'COX4I1', 'TMED2', 'NBEAL1', 'SNORD18C', 'FNTA', 'RPS25', 'RPL37', 'HINT1', 'EEF2', 'RPS10', 'ATP6V0E1', 'HNRNPK', 'ANAPC5', 'SNORD73A', 'HNRNPU', 'HNRNPU', 'EIF3A', 'EIF3A', 'EIF3A', 'MIR3652', 'MIR3652', 'MSN', 'ACTN4', 'APP', 'PRKAR1A', 'PRKAR1A', 'PRKAR1A', 'DSP', 'RAD21', 'RAD21', 'WDR1', 'NCL', 'WDR1', 'AP2B1', 'AP2M1', 'CLTC', 'AP2B1', 'MLEC', 'MLEC', 'LASP1', 'SF3B2', 'TMEM59', 'CSRP1', 'CALM3', 'CALM3', 'SNHG4', 'CAP1', 'SNHG4', 'PTGES3', 'WARS', 'WARS', 'SETSIP', 'SETSIP', 'NDRG1', 'UBB', 'PFN1', 'PTPRF', 'PTPRF', 'PTPRF', 'YWHAZ', 'YWHAZ', 'YWHAZ', 'YWHAZ', 'SOD1', 'HDLBP', 'MARCKSL1', 'GABARAP', 'NUCB1', 'EIF3CL', 'GLUL', 'NUCB1', 'LDHA', 'SNORD96A', 'SSR2', 'CALM3', 'P4HB', 'CALM3', 'P4HB', 'SLC25A5', 'PHB', 'PHB', 'S100A11', 'CTSA', 'TOMM20', 'CD63', 'DNAJB1', 'SPARC', 'DNAJB1', 'UBE2D3', 'UBE2D3', 'UBE2D3', 'XBP1', 'SPTBN1', 'SPTBN1', 'LAPTM4A', 'RPL32', 'CD81', 'UBE2L3', 'PTTG1IP', 'GRN', 'HMGB1', 'HMGB1', 'GLO1', 'UBE2L3', 'UBE2L3', 'UBE2L3', 'SRSF11', 'SRSF11', 'SF3B3', 'SF3B3', 'MIR3654', 'HSPA9', 'HSPA9', 'HSPA9', 'YWHAQ', 'DDX24', 'PPP2R1A', 'GSN', 'HK1', 'KDELR2', 'KDELR2', 'KDELR2', 'NPC2', 'DDX24', 'DYNLL1', 'LITAF', 'SNORA41', 'LITAF', 'PRKCSH', 'GOT2', 'LOC101929368', 'ACADVL', 'SKP1', 'MAPRE1', 'MAPRE1', 'OS9', 'SNORD32A', 'RPL13AP5', 'RPL7', 'SKP1', 'SKP1', 'ACTR1A', 'ACTR1A', 'CAPRIN1', 'CAPRIN1', 'SNORA70', 'SNORA70', 'PPP1CC', 'ACTR2', 'ACTR2', 'ACTR2', 'PTP4A1', 'PTP4A1', 'PTP4A1', 'PTP4A1', 'ARF3', 'NACA', 'GPX1', 'PGK1', 'PGK1', 'SUMO3', 'SUMO3', 'RPS27', 'TPP1', 'TPP1', 'GNB1', 'GNB1', 'GNB1', 'NUMA1', 'FTH1', 'RAN', 'RAN', 'HNRNPC', 'CAPN1', 'MIR636', 'MIR636', 'CALU', 'CALU', 'CALU', 'NFE2L1', 'NFE2L1', 'ARL6IP5', 'ARL6IP5', 'DPYSL2', 'RPLP1', 'CTNNA1', 'CTNNA1', 'CTSD', 'FAM120A', 'MAT2A', 'MAT2A', 'LAMC1', 'LAMC1', 'LOC100506248', 'PTMA', 'FAM120A', 'HNRNPK', 'BZW1', 'BZW1', 'SEPT2', 'ATF4', 'GNAS', 'RPS15A', 'ANXA5', 'STMN1', 'LRP1', 'LRP1', 'PSMB7', 'PEA15', 'PEA15', 'ECH1', 'ODC1', 'IQGAP1', 'XRCC6', 'ACO2', 'DAZAP2', 'SPARCL1', 'MCL1', 'MCL1', 'MCL1', 'HSPA1B', 'HSPA1L', 'ACTB', 'SARS', 'TMBIM6', 'TMBIM6', 'LMAN2', 'HSPD1', 'HSPD1', 'ZYX', 'RPL12', 'CIRBP', 'CIRBP', 'CCT7', 'PAFAH1B1', 'PSME1', 'PAFAH1B1', 'PAFAH1B1', 'RPS10', 'ATP5O', 'RPS15', 'PSMD8', 'LAMP2', 'TPI1', 'RPL29', 'GSTP1', 'HYOU1', 'SNRPD2', 'PLOD1', 'ZNF207', 'ZNF207', 'PSMD2', 'SCD', 'SCD', 'RAP1B', 'RPS21', 'MAP4', 'MAP4', 'BCAP31', 'CTSB', 'CTSB', 'KARS', 'EPRS', 'EPRS', 'EPRS', 'PRDX6', 'PRDX6', 'PPP1CA', 'SARAF', 'AHCYL1', 'AHCYL1', 'AHCYL1', 'IST1', 'GNB2', 'H2AFZ', 'NCOR1', 'NCOR1', 'NCOR1', 'NCOR1', 'SNORD38B', 'FLNA', 'CNOT1', 'CNOT1', 'DHCR24', 'RAB11A', 'RAB11A', 'EIF3F', 'PSAP', 'RNF114', 'RNF114', 'SNORA68', 'STRAP', 'PSAP', 'S100A10', 'CCT8', 'MIR1292', 'MIR1292', 'PSMB1', 'CCT4', 'EPAS1', 'EPAS1', 'DNAJA1', 'DNAJA1', 'PSMD4', 'UQCRC2', 'CKB', 'RHOC', 'PGAM1', 'STAT1', 'SNORA21', 'SSR1', 'SSR1', 'SSR1', 'TRA2B', 'TRA2B', 'FKBP4', 'FKBP4', 'HDGF', 'PALLD', 'MGEA5', 'MGEA5', 'M6PR', 'M6PR', 'SEP15', 'AHCY', 'HLA-E', 'HLA-E', 'PALLD', 'PALLD', 'RPLP2', 'SNORA52', 'LOC101927137', 'TACC1', 'MIR1248', 'PPM1G', 'KTN1', 'KTN1', 'TAGLN2', 'SRPRA', 'SRPRA', 'PHC2', 'BTG1', 'BTG1', 'KDELR1', 'LGALS3BP', 'SLC3A2', 'COX6A1', 'RPS23', 'RAB14', 'RAB14', 'TMED10', 'VCL', 'VCL', 'DCTN2', 'RPS4X', 'DEK', 'CALR', 'RPL8', 'RPL5', 'RERE', 'RERE', 'RERE', 'HSBP1', 'HSBP1', 'HMGN1', 'LOC101927733', 'SEC31A', 'GLUD1', 'GLUD1', 'MLF2', 'SNORD54', 'ARPC1A', 'CCND2', 'CCND2', 'CCND2', 'ATP6V0C', 'IMMT', 'SSRP1', 'SSRP1', 'SDCBP', 'FUS', 'CLTA', 'SEPHS2', 'RPL31', 'RPL31', 'UBA1', 'ABLIM1', 'ALDOA', 'PPIB', 'PPIB', 'SERP1', 'SERP1', 'SERP1', 'TSPAN3', 'TSPAN3', 'ACTA2', 'PPT1', 'TAX1BP1', 'TAX1BP1', 'MDH1', 'PDHA1', 'PDHA1', 'GNAS', 'ANXA6', 'CD59', 'CD59', 'CD59', 'SERPING1', 'PSME3', 'PSME3', 'HIF1A', 'TRIM28', 'SNX17', 'IPO7', 'IPO7', 'IPO7', 'IPO7', 'ACTR3', 'RBM14-RBM4', 'CKAP4', 'CKAP4', 'AARS', 'TMEM189-UBE2V1', 'TMEM189-UBE2V1', 'TMEM189-UBE2V1', 'SSR4', 'CD9', 'PRDX2', 'HADHB', 'TXNIP', 'TXNIP', 'TXNIP', 'RPN1', 'ANXA1', 'PAICS', 'PAICS', 'JUP', 'EIF1AX', 'EIF1AX', 'EIF1AX', 'EIF1AX', 'YWHAH', 'DSTN', 'DSTN', 'TAF7', 'EIF5B', 'EIF5B', 'EIF5B', 'EIF5B', 'CD99', 'CD99', 'LDHB', 'HNRNPH1', 'BLCAP', 'RPLP0', 'ADD3', 'HADH', 'HADH', 'PFKP', 'ANP32A', 'RAD23A', 'GNAI2', 'DUSP1', 'TGM2', 'ANP32A', 'DUSP1', 'WTH3DI', 'RAD23A', 'WTH3DI', 'WTH3DI', 'RPS18', 'PLD3', 'ANP32A', 'PSMF1', 'PSMF1', 'HNRNPA0', 'HNRNPA0', 'GOLGB1', 'GOLGB1', 'MYL9', 'CTTN', 'STOM', 'STOM', 'STOM', 'RCN1', 'LOC100996696', 'GTF2IP4', 'CYC1', 'PSMC2', 'PSMC2', 'MMP2', 'SF3B1', 'SF3B1', 'SMARCC1', 'SMARCC1', 'SMARCC1', 'SMARCC1', 'SNU13', 'SNU13', 'TM9SF2', 'SYNGR2', 'PIP4K2B', 'PIP4K2B', 'SLC4A5', 'BCLAF1', 'BCLAF1', 'SON', 'SON', 'PXN', 'KPNA2', 'ATP6V1B2', 'TUBA1B', 'CBX3', 'RBBP7', 'SDHA', 'RPS29', 'DAP', 'ARF4', 'ARF4', 'COPB2', 'USP9X', 'USP9X', 'BCLAF1', 'PFKL', 'NBPF20', 'NBPF25P', 'LGALS1', 'GPX4', 'THBS1', 'THBS1', 'THBS1', 'THBS1', 'CSE1L', 'CSE1L', 'TUFM', 'PSMA7', 'POLD2', 'CPE', 'CPE', 'PGD', 'COX8A', 'PGRMC1', 'PGRMC1', 'EIF5A', 'EIF5A', 'ITGB5', 'ITGB5', 'MGAT1', 'ACLY', 'ACLY', 'SRSF7', 'CDH1', 'CDH1', 'RPL36A-HNRNPH2', 'PJA2', 'COX7C', 'ECHS1', 'PLP2', 'HLA-DPB1', 'SSB', 'SSB', 'RAB5C', 'GPNMB', 'EIF2S1', 'EIF2S1', 'EIF2S1', 'HAX1', 'NFE2L2', 'TIMP3', 'TIMP3', 'TIMP3', 'TIMP3', 'MBNL1', 'MBNL1', 'MBNL1', 'SNORD18C', 'MFN2', 'RAB5C', 'NMT1', 'NMT1', 'NMT1', 'YBX3', 'YBX3', 'IGFBP7', 'IGFBP7', 'PUM1', 'PUM1', 'PUM1', 'ARHGDIA', 'ARHGDIA', 'BHLHE40', 'BHLHE40', 'ATP6V0E1', 'ATP6V0E1', 'NUDC', 'TERF2IP', 'TMX2', 'ARCN1', 'UBA2', 'FBXO7', 'GNAI3', 'GNAI3', 'GNAI3', 'CHD4', 'CHD4', 'CHD4', 'HTRA1', 'LRPAP1', 'ITPR3', 'ITPR3', 'ITPR3', 'PITPNA', 'PITPNA', 'PITPNA', 'IDH1', 'SEPW1', 'SLC7A5', 'AMD1', 'AMD1', 'PSMD1', 'PSMD1', 'CREG1', 'CSTB', 'PCNA', 'RRBP1', 'RRBP1', 'RRBP1', 'RRBP1', 'TNFAIP1', 'TNFAIP1', 'HDAC1', 'DDX3X', 'DDX3X', 'LGMN', 'PPP1R7', 'PPP1R7', 'PLS3', 'ERP29', 'SNORD83B', 'CTBP2', 'CTBP2', 'CTBP2', 'SNRNP70', 'RAD23B', 'RAD23B', 'SRRM1', 'SRRM1', 'NDUFB8', 'NDUFB8', 'ARIH2', 'ARIH2', 'ARIH2', 'ENO1', 'PSMD13', 'PSMD13', 'ILK', 'BTG2', 'BTG2', 'CAPZA2', 'CAPZA2', 'SPCS2', 'SPCS2', 'DDX1', 'ATP1B1', 'ATP1B1', 'RAF1', 'LOC101927673', 'LOC101927673', 'SREBF2', 'SREBF2', 'SLC2A1', 'SLC2A1', 'PKM', 'PSMC4', 'CDIPT', 'RPS6', 'BAG6', 'COX7A2L', 'SNORD73A', 'RPS16', 'SYPL1', 'SYPL1', 'BGN', 'BGN', 'TARS', 'COPE', 'AF119897', 'TXNRD1', 'PSMC3', 'NME1-NME2', 'NUDCD3', 'NUDCD3', 'RALY', 'AKR1B1', 'SRP9', 'PSMA5', 'FDPS', 'RAB5B', 'HNRNPAB', 'LOC101926921', 'LOC101926921', 'LOC101926921', 'ADRM1', 'OGDH', 'TRAK1', 'APEH', 'MKRN1', 'SDC1', 'SDC1', 'ARHGDIB', 'CYR61', 'SEC11A', 'TOP2A', 'TOP2A', 'LOC101060363', 'WSB1', 'WSB1', 'WSB1', 'MOB1A', 'MOB1A', 'MOB1A', 'PRNP', 'ANXA4', 'ANXA4', 'EIF4A3', 'NDUFA5', 'ANP32B', 'ANP32B', 'SEPT11', 'SEPT11', 'NREP', 'NREP', 'SH3BGRL', 'SH3BGRL', 'ENO2', 'STK25', 'IFITM2', 'PSMA2', 'PSMA2', 'MYL12B', 'MYL12A', 'SMARCC2', 'SMARCC2', 'ATP5B', 'MIR6733', 'EMP1', 'EMP1', 'CCT6A', 'CCT6A', 'ETS2', 'ETS2', 'RARS', 'STAT6', 'STAT6', 'ARHGEF12', 'ARHGEF12', 'ARHGEF12', 'VAMP3', 'VAMP3', 'GTF3A', 'SCP2', 'ENC1', 'ENC1', 'SNRPC', 'UBE2D2', 'UBE2D2', 'UBE2D2', 'ADIPOR2', 'GRHPR', 'GPX3', 'SLC9A3R1', 'FLOT2', 'YME1L1', 'YME1L1', 'BAZ2A', 'BAZ2A', 'BAZ2A', 'SF3A1', 'SF3A1', 'COPB1', 'COPB1', 'CST3', 'TMEM109', 'IVNS1ABP', 'IVNS1ABP', 'OAZ2', 'OAZ2', 'ANXA7', 'ZFP36L2', 'ZFP36L2', 'ZFP36L2', 'CUL3', 'CUL3', 'CUL3', 'PLEC', 'PPP2CB', 'PPP2CB', 'HNRNPF', 'UBAP2L', 'UBAP2L', 'TPD52L2', 'CRTAP', 'CACYBP', 'CACYBP', 'NBR1', 'NBR1', 'DHX15', 'DHX15', 'UCHL1', 'PSMD3', 'ITGA5', 'CSNK2B', 'TRAP1', 'IGF2R', 'IGF2R', 'RBM5', 'RBM5', 'SGTA', 'PHGDH', 'TRAM1', 'TRAM1', 'PSMB3', 'GRK2', 'GRK2', 'MGST3', 'PSMB2', 'COPS6', 'RPL36A-HNRNPH2', 'PPP1CB', 'PPP1CB', 'PPP1CB', 'PLEKHB2', 'PLEKHB2', 'LRP10', 'HSD17B4', 'NAP1L4', 'GSS', 'SOX4', 'SOX4', 'SOX4', 'BAP1', 'WDR77', 'WDR77', 'IFI30', 'CUL4A', 'CUL4A', 'ALDH2', 'VIM', 'SEPP1', 'CLDN4', 'RPL37A', 'DPYSL3', 'DPYSL3', 'CAT', 'PTDSS1', 'TTC1', 'EIF4E', 'EIF4E', 'EIF4E', 'COL6A3', 'GBF1', 'DDX23', 'COX6B1', 'ATP6AP2', 'ATP6AP2', 'ATP6AP2', 'CNN3', 'TIA1', 'TIA1', 'TIA1', 'TIA1', 'TIA1', 'RHEB', 'RHEB', 'RHEB', 'NPEPPS', 'NPEPPS', 'BUB3', 'BUB3', 'BUB3', 'RUVBL2', 'MAPKAPK2', 'MAPKAPK2', 'SCRN1', 'TALDO1', 'JUN', 'JUN', 'JUN', 'NQO1', 'NQO1', 'SHC1', 'GSTO1', 'SQSTM1', 'VBP1', 'JUNB', 'ITGA3', 'MIR6758', 'RRM1', 'RRM1', 'MIR664B', 'MIR664B', 'SUPT5H', 'PYGB', 'QSOX1', 'SUPT4H1', 'SUPT4H1', 'RCN2', 'RCN2', 'CTSC', 'KHDRBS1', 'PPIF', 'PPIF', 'AHSA1', 'RPL41', 'PUM2', 'PRCP', 'MYH11', 'MYH11', 'MYH11', 'USP7', 'USP7', 'PPP1R11', 'GRSF1', 'NFKBIA', 'G3BP1', 'TSN', 'LAMB1', 'TGFBI', 'PFDN1', 'IGFBP4', 'IDH3B', 'ELF3', 'AAMP', 'TOMM70', 'TSN', 'G3BP1', 'TSN', 'SRM', 'NCBP2', 'CBX1', 'TOMM70', 'GRSF1', 'NCBP2', 'SNURF', 'UBE2N', 'UBE2N', 'APOD', 'ARF5', 'LOC101927180', 'RPA1', 'RPA1', 'LOC101928634', 'ZFP36', 'PSMA3', 'CTNNB1', 'UBL3', 'UBL3', 'DUSP3', 'DUSP3', 'DUSP3', 'FHL1', 'FHL1', 'ZNHIT1', 'SAR1A', 'SAR1A', 'BCL2L2-PABPN1', 'BCL2L2-PABPN1', 'TRIP12', 'KDM5B', 'KDM5B', 'KDM5B', 'ACTG1', 'LAMP1', 'LAMP1', 'LAMP1', 'GYG1', 'MCM3', 'VAMP2', 'VAMP2', 'RAE1', 'CLIC4', 'CLIC4', 'CLSTN1', 'SORD', 'SORD', 'FSCN1', 'ID2', 'ID2', 'GOLGA4', 'UQCRQ', 'SAMM50', 'SAMM50', 'DCTD', 'DCTD', 'ETF1', 'ETF1', 'SNW1', 'TMPPE', 'NME1', 'PODXL', 'FAT1', 'TMX4', 'TMX4', 'SEC23B', 'SEC23B', 'DDX39A', 'SFPQ', 'SFPQ', 'IRAK1', 'TXNL1', 'SMC1A', 'ANXA2', 'NISCH', 'EIF3H', 'ZC3H15', 'PPP4R1', 'ZC3H15', 'KRT18', 'COX7A2', 'INPPL1', 'OAT', 'PHB2', 'IFITM2', 'PPP1R12A', 'PPP1R12A', 'PPP1R12A', 'CNN2', 'PWP1', 'PWP1', 'PWP1', 'ICMT', 'ICMT', 'ICMT', 'ALDH9A1', 'AP1G2', 'RUVBL1', 'CALD1', 'CALD1', 'CALD1', 'GPAA1', 'PRDX3', 'MBTPS1', 'NBL1', 'SND1', 'DARS', 'DARS', 'INSIG1', 'INSIG1', 'INSIG1', 'RRAGA', 'ACP1', 'ACP1', 'IER3', 'EIF2B1', 'CYB5B', 'CYB5B', 'FXR1', 'FXR1', 'FXR1', 'CPSF1', 'MIR6849', 'CLPTM1', 'BST2', 'IFNGR2', 'KDM3B', 'TSTA3', 'TNC', 'SCARB2', 'SCARB2', 'JAK1', 'UBE2L6', 'KRT19', 'PACSIN2', 'COPS5', 'CNIH1', 'HSPG2', 'HSPG2', 'ITGA6', 'ARL1', 'ARL1', 'ARL1', 'ACSL3', 'ACSL3', 'ACSL3', 'SMC4', 'SMC4', 'RPS17', 'TIMP1', 'GJA1', 'MARCKS', 'MARCKS', 'MARCKS', 'USP14', 'USP14', 'GYS1', 'AKAP1', 'AKAP1', 'PSMA1', 'HMCES', 'HMCES', 'SRRT', 'SRRT', 'DLG5', 'PMPCB', 'TOX4', 'TOX4', 'TOX4', 'API5', 'API5', 'TPD52', 'TPD52', 'TPD52', 'TPD52', 'SIGMAR1', 'EGR1', 'EGR1', 'PNP', 'SRSF4', 'DNMT1', 'GATC', 'PSMC6', 'CCND3', 'PGRMC2', 'PPP1R10', 'PPP1R10', 'ENTPD6', 'PSMD7', 'PEX19', 'PEX19', 'NIPSNAP1', 'NIPSNAP1', 'MYBL2', 'RANBP2', 'RANBP2', 'RANBP2', 'TUBG1', 'ACIN1', 'SNX1', 'MRPL49', 'EPB41L2', 'EPB41L2', 'LAPTM5', 'LAPTM5', 'GALNT1', 'GALNT1', 'GALNT1', 'CDC123', 'ELAVL1', 'ELAVL1', 'KIAA0100', 'KIAA0100', 'TPR', 'TPR', 'CLCN3', 'CLCN3', 'CLCN3', 'CLCN3', 'MARCH6', 'MARCH6', 'EIF1B', 'SGK1', 'NDUFS3', 'SRSF1', 'SRSF1', 'CD14', 'LUM', 'TWF1', 'TP53', 'SAFB', 'SAFB', 'ECE1', 'ECE1', 'JOSD1', 'ADD3', 'ADD3', 'COX6C', 'MCM5', 'RPA2', 'RPL10', 'TSG101', 'TBCD', 'WSB2', 'MTHFD2', 'MIR7703', 'DAXX', 'TMEM106C', 'HEXA', 'ELAC2', 'ELAC2', 'CLINT1', 'CLINT1', 'SNRPA', 'SCAMP3', 'AZIN1', 'ADNP', 'NCAPD2', 'EFCAB14', 'EFCAB14', 'EFCAB14', 'EFCAB14', 'RNF13', 'RNF13', 'AIP', 'AIP', 'RELA', 'C11orf58', 'RNASE1', 'ADAR', 'FBLN1', 'DDX42', 'PCNX4', 'DHCR7', 'DHCR7', 'AEBP1', 'SMG7', 'SMG7', 'LBR', 'VARS', 'VARS', 'MYOF', 'OSBP', 'OSBP', 'SLC29A1', 'SLC29A1', 'POLR2B', 'TBCB', 'PRKAG1', 'ATXN2L', 'VPS26A', 'ENG', 'ENG', 'SH3BP5', 'SH3BP5', 'C4orf46', 'TBC1D5', 'TBC1D5', 'TBC1D5', 'GBAS', 'UBE3C', 'LPCAT1', 'SCARB1', 'KRT5', 'TIMM17A', 'TIMM17A', 'RNF14', 'RNF14', 'SCCPDH', 'SCCPDH', 'SMARCD2', 'FAM127A', 'NET1', 'NET1', 'USO1', 'USO1', 'HDAC2', 'PRKAB1', 'PRKAB1', 'SUPT7L', 'SUPT7L', 'SUPT7L', 'EPCAM', 'NEDD8', 'HSPB1', 'EFEMP1', 'EFEMP1', 'RYBP', 'RYBP', 'RYBP', 'LIPA', 'BNIP3', 'BNIP3', 'CAPG', 'SH3GL1', 'COL3A1', 'CDC25B', 'ATMIN', 'ATMIN', 'ZFR', 'ZFR', 'SRGN', 'SRGN', 'PLAT', 'LRRFIP1', 'LRRFIP1', 'FAM32A', 'GDI1', 'NR3C1', 'NR3C1', 'TBL1X', 'TBL1X', 'TBL1X', 'TOMM34', 'UBXN1', 'ABCE1', 'ABCE1', 'MPZL1', 'MPZL1', 'PON2', 'PPP2R5C', 'ARIH1', 'ARIH1', 'ARIH1', 'ARIH1', 'B4GALT1', 'B4GALT1', 'CEACAM5', 'CYB5R3', 'DCAF11', 'IL13RA1', 'IL13RA1', 'FAM3C', 'RRM2', 'B2M', 'IMPDH2', 'DCN', 'SSR1', 'ARAF', 'PSRC1', 'CKS1B', 'UBE2A', 'UBE2A', 'AKR1A1', 'YY1', 'YY1', 'UQCRC1', 'CTDSPL', 'CTDSPL', 'CTDSPL', 'DVL3', 'DVL3', 'RPS4Y1', 'FARP1', 'FARP1', 'GSPT1', 'COASY', 'SEC63', 'SEC63', 'SEC63', 'SLC25A36', 'SLC25A36', 'SLC25A36', 'SLC20A1', 'GNG10', 'NSA2', 'PRDX4', 'AFF1', 'CD55', 'CD55', 'PKP4', 'PKP4', 'PKP4', 'MCM6', 'ETFA', 'LRRC41', 'CHMP1A', 'WDR82', 'EIF4G3', 'EIF4G3', 'DNPEP', 'CDK2AP1', 'PLK2', 'CPD', 'CPD', 'CPD', 'CPD', 'HEXB', 'FURIN', 'CCT2', 'CCT2', 'GNL2', 'CAPZB', 'CAPZB', 'ALCAM', 'ALCAM', 'CIB1', 'ARPC1B', 'CCNC', 'GNPAT', 'PPP1R12B', 'PPP1R12B', 'MYCBP2', 'MYCBP2', 'RNF41', 'RNF41', 'ACSL1', 'SETX', 'SETX', 'NDUFS2', 'RBM6', 'PGM1', 'NASP', 'NASP', 'ATP6V1A', 'ATP6V1A', 'CCZ1B', 'CCZ1', 'CLIP1', 'MYO10', 'KIAA0141', 'KIAA0141', 'PPP5C', 'RSU1', 'PAPPA', 'PAPPA', 'EGFR', 'EGFR', 'KIAA0196', 'MED13', 'MED13', 'CREBL2', 'CREBL2', 'CREBL2', 'KIF5B', 'KIF5B', 'HNRNPDL', 'MORF4L2', 'EXT1', 'SPEN', 'SPEN', 'ST6GAL1', 'DYNLT1', 'NDUFA6', 'NDUFA6', 'ACAA2', 'ACAA2', 'SDHC', 'ST14', 'PTPN12', 'NID1', 'NID1', 'TWF2', 'PTGR2', 'TJP1', 'EXT2', 'EXT2', 'PPP1R15A', 'METAP2', 'MEST', 'EPHX1', 'LTF', 'LANCL1', 'LANCL1', 'EIF1', 'ALDOC', 'EFNA1', 'ASNA1', 'ACAA1', 'SDHD', 'TMEM184B', 'RPL38', 'RPL38', 'BCKDK', 'WIPI2', 'MAN2A2', 'RB1CC1', 'RB1CC1', 'SFRP1', 'SFRP1', 'SFRP1', 'UBE4A', 'MYO18A', 'KDM5A', 'FIBP', 'LOC101928623', 'SMS', 'ARHGAP35', 'ARHGAP35', 'ARHGAP35', 'CBX6', 'CBX6', 'ZMYM4', 'ZMYM4', 'ZMYM4', 'RAI14', 'ALDH3A2', 'ALDH3A2', 'KPNA1', 'KPNA1', 'KPNA1', 'KPNA1', 'KPNA1', 'CTR9', 'SEL1L', 'SEL1L', 'SEL1L', 'SEL1L', 'PPFIA1', 'PPFIA1', 'LDLR', 'LDLR', 'IDH3A', 'IDH3A', 'SDC4', 'HNRNPL', 'OPTN', 'OPTN', 'PLTP', 'BIRC2', 'NDUFAB1', 'COPS3', 'TRAK1', 'TRAK1', 'IER2', 'SEC14L1', 'SEC14L1', 'SEC14L1', 'TJP2', 'MX1', 'CTSL', 'SLC39A6', 'SLC39A6', 'UQCR11', 'ARL2BP', 'ARL2BP', 'PAF1', 'BIRC5', 'BIRC5', 'TSPO', 'NUP153', 'PRMT2', 'DGCR2', 'RALB', 'RALB', 'BRD4', 'BRD4', 'LOC101930112', 'IGBP1', 'GOLGA3', 'MCM2', 'PEPD', 'ARFIP2', 'COX7B', 'SLC4A2', 'VWF', 'SNX2', 'SNX2', 'NOC2L', 'DPF2', 'ARHGAP1', 'CPNE3', 'CPNE3', 'AP2S1', 'CHMP2A', 'PLIN3', 'ABL1', 'TRAK2', 'TRAK2', 'PRPF4B', 'PRPF4B', 'AREL1', 'RIOK3', 'RIOK3', 'RIOK3', 'WWTR1', 'WWTR1', 'WWTR1', 'ACTR1B', 'ZMYND11', 'ZMYND11', 'AIMP2', 'AKR7A2', 'CLK3', 'COPS8', 'COPS8', 'COPS8', 'ADSL', 'LY6E', 'IFRD1', 'IFRD1', 'PYCR1', 'NEDD9', 'NEDD9', 'UBAC1', 'USF2', 'NUP62', 'TUBB3', 'NUP214', 'CELF2', 'CELF2', 'CELF2', 'FARSA', 'CREBBP', 'PKN1', 'CNOT8', 'CNOT8', 'CNOT8', 'PPP1R2', 'PPP1R2', 'MMS19', 'AK6', 'AASDHPPT', 'AASDHPPT', 'VEZF1', 'VEZF1', 'VEZF1', 'PCM1', 'CHPF', 'ERCC3', 'GAS6', 'PRKCZ', 'BLMH', 'MVP', 'SUSD6', 'KAT2A', 'KIF22', 'NUP133', 'PLOD3', 'PPP2R5A', 'PPP2R5A', 'NUP93', 'MIR4745', 'CSTF1', 'GAS7', 'GAS7', 'LIMK2', 'TMED5', 'TMED5', 'DKK3', 'MTMR3', 'MTMR3', 'SRPK1', 'SRPK1', 'BLVRB', 'LAMA4', 'AMFR', 'AMFR', 'VASP', 'ARL4C', 'ARL4C', 'ARL4C', 'LSM3', 'GSK3A', 'ARFGAP3', 'PES1', 'CUL4B', 'CUL4B', 'NFYC', 'NFYC', 'C21orf33', 'FADS2', 'SLC6A8', 'KIAA0907', 'EP300', 'DES', 'STT3A', 'CRK', 'CRK', 'CRK', 'BRD8', 'NPTN', 'CHERP', 'CHERP', 'EIF3M', 'EIF3M', 'UQCRHL', 'SLC16A1', 'SLC16A1', 'SLC16A1', 'LOC101928916', 'LOC101928916', 'PARP4', 'PLK1', 'TRIB1', 'TSPAN7', 'PSMB4', 'PSMB4', 'LSS', 'CDK4', 'MTA1', 'E2F4', 'DCAF8', 'DCAF8', 'PRPF3', 'RAB13', 'DNM2', 'SIPA1L1', 'SIPA1L1', 'CD2BP2', 'CD2BP2', 'N4BP2L2', 'N4BP2L2', 'STXBP1', 'VPS72', 'DDAH2', 'CYB5R1', 'TOMM40', 'COMMD3-BMI1', 'TDP2', 'LAMC2', 'NAE1', 'GBP1', 'GBP1', 'FBXO28', 'FBXO28', 'PDGFRB', 'ACTG2', 'G6PD', 'SHFM1', 'SPTLC1', 'SPTLC1', 'C14orf2', 'GAK', 'GAK', 'HSD17B10', 'SERPINF1', 'CDKN1A', 'TACSTD2', 'TACSTD2', 'TACSTD2', 'MTOR', 'TACC2', 'PDAP1', 'MGP', 'LYPLA2', 'STAG1', 'STAG1', 'CTSH', 'RER1', 'RER1', 'NDUFA1', 'LAMTOR5', 'LAMTOR5', 'RSRC2', 'RSRC2', 'SMARCA5', 'FNDC3A', 'FEZ2', 'POLR2G', 'TAP1', 'SREBF1', 'MTHFD1', 'COL1A1', 'COL1A1', 'COL1A1', 'PPP2R2A', 'LRRD1', 'BCR', 'UBE4B', 'UBE4B', 'SENP6', 'SENP6', 'GTF3C1', 'GGPS1', 'GGPS1', 'ACBD3', 'ACBD3', 'ATP5J', 'EHMT2', 'LOC101930075', 'LOC101930075', 'CSK', 'UNG', 'BCKDHA', 'LOC400927-CSNK1E', 'UBE2B', 'UBE2B', 'UBE2B', 'PAM', 'PMF1', 'TK1', 'SYMPK', 'NR4A1', 'TRIM2', 'TRIM2', 'COX5B', 'HSF1', 'FABP5', 'UBE2K', 'UBE2K', 'TOR1A', 'TOR1A', 'LOC100506558', 'ITGAV', 'PSMD12', 'PSMD12', 'GTF2F1', 'GTF2F1', 'GTF2F1', 'CFB', 'SNX19', 'SNX19', 'MAML1', 'SEC24C', 'RAP1A', 'SPOCK1', 'MXI1', 'UNC119B', 'ACADS', 'CUX1', 'TRAM2', 'TRAM2', 'CBFB', 'TCEAL4', 'RAB3GAP2', 'RAB3GAP2', 'RAB3GAP2', 'SEC24D', 'SERPINA3', 'LEPROT', 'LEPROT', 'NKTR', 'NKTR', 'ADAM9', 'GNPDA1', 'KDM5C', 'TCOF1', 'TCOF1', 'KIAA0430', 'BAG1', 'RGS2', 'HTT', 'HTT', 'BASP1', 'MIR7109', 'KLF10', 'ABCF3', 'LOC101930324', 'TCERG1', 'NUTF2P4', 'C15orf38-AP3S2', 'C15orf38-AP3S2', 'SRF', 'SRF', 'CARS', 'COL1A2', 'COL1A2', 'TIAL1', 'TIAL1', 'PRPF31', 'PRPF31', 'INS-IGF2', 'INS-IGF2', 'IFI27', 'USP1', 'USP1', 'ERCC5', 'HSPBP1', 'DNAJC7', 'KEAP1', 'YIF1A', 'KDSR', 'DHX9', 'IGSF3', 'ACSL4', 'KAT6A', 'MAP2K2', 'PPP3CA', 'RXRA', 'MPC2', 'DBI', 'PPP3CA', 'PLSCR1', 'MYC', 'PPP3CB', 'SLC35B1', 'CYP1B1', 'CYP1B1', 'CYP1B1', 'CYP1B1', 'IDS', 'IDS', 'ST5', 'ERLIN1', 'AP3S1', 'NOTCH2', 'ERLIN1', 'NOTCH2', 'PLSCR1', 'DECR1', 'ZER1', 'RXRA', 'CTSK', 'GTF2H1', 'ZER1', 'GTF2H1', 'ERBB3', 'HDAC5', 'ZER1', 'PPP3CA', 'PRSS23', 'LPIN2', 'LPIN2', 'EIF2B2', 'DDX46', 'MBD3', 'PFKFB3', 'PCOLCE', 'PAPD7', 'COPS2', 'CTNNAL1', 'CPSF6', 'CPSF6', 'IDH3G', 'MPI', 'HCFC1', 'HCFC1', 'TMEM147', 'TUBGCP2', 'TUBGCP2', 'TRIB2', 'TRIB2', 'DEDD', 'DHRS3', 'RANBP1', 'RANBP1', 'MBD2', 'MBD2', 'AFG3L2', 'H2AFV', 'FXYD3', 'FXYD3', 'IKBKAP', 'IKBKAP', 'ATG9A', 'GH1', 'PPIE', 'TBCC', 'EDC4', 'SLC2A3', 'SLC2A3', 'SLC2A3', 'DNAJB2', 'MAPRE2', 'ACADM', 'KIAA0101', 'TRIM29', 'SNRPB2', 'SSFA2', 'SNAP25', 'SNAP25', 'TNFAIP2', 'TNFAIP2', 'ATG5', 'ATG5', 'PPP2R5D', 'DLG1', 'DLG1', 'DLG1', 'CRMP1', 'BCL7B', 'MLXIP', 'MLH1', 'CTCF', 'PITPNB', 'SPOCK2', 'SPOCK2', 'PRSS8', 'SMAD4', 'SMAD4', 'GALE', 'PRPSAP1', 'MAPK14', 'IRF1', 'DHFR', 'DHFR', 'DHFR', 'FADD', 'CHMP2B', 'CHMP2B', 'CHMP2B', 'HMGCR', 'HMGCR', 'AIMP1', 'AIMP1', 'GMFB', 'GMFB', 'PRKCD', 'VAMP8', 'ARHGEF7', 'ARHGEF7', 'VAPB', 'VAPB', 'LOC101929500', 'LOC101929500', 'SYF2', 'GSTM3', 'MYLK', 'MCRS1', 'HSPA13', 'HSPA13', 'CHTOP', 'CHTOP', 'TNKS', 'C14orf1', 'C14orf1', 'ARL2', 'SVIL', 'SVIL', 'SNRPD3', 'MARK3', 'MARK3', 'DLGAP4', 'DLGAP4', 'DLGAP4', 'CSNK1G2', 'CSNK1G2', 'CRABP2', 'DDX19A', 'DDX19A', 'DDX19A', 'HMGN4', 'FOXM1', 'HSPA1B', 'RANBP9', 'RANBP9', 'NFX1', 'NFX1', 'POLR2L', 'AK1', 'AK1', 'TYMS', 'PDK2', 'SSBP1', 'BLOC1S1', 'GDE1', 'LEPROTL1', 'LEPROTL1', 'ENSA', 'IRF6', 'S100A13', 'NRIP1', 'NRIP1', 'HTATSF1', 'HTATSF1', 'ADAM10', 'ADAM10', 'GUSB', 'TLK1', 'NDST1', 'NDST1', 'EPS8', 'MED14', 'MED14', 'MED14', 'CTPS1', 'SLC30A9', 'GNAQ', 'MECP2', 'MECP2', 'MECP2', 'PLOD2', 'PLOD2', 'IRF3', 'ATXN2', 'EAPP', 'CABIN1', 'LYN', 'LYN', 'SERPINE1', 'SERPINE1', 'APPBP2', 'APPBP2', 'APPBP2', 'OVC

In [46]:
iden = iden.drop(0)

In [43]:
row_list = list(df_identifier.columns)

print(row_list)
iden_probe = pd.DataFrame({'prob_iden': row_list})

['Unnamed: 0', '1007_s_at', '1053_at', '117_at', '121_at', '1255_g_at', '1294_at', '1316_at', '1320_at', '1405_i_at', '1431_at', '1438_at', '1487_at', '1494_f_at', '1598_g_at', '160020_at', '1729_at', '1773_at', '177_at', '179_at', '1861_at', '200000_s_at', '200001_at', '200002_at', '200003_s_at', '200004_at', '200005_at', '200006_at', '200007_at', '200008_s_at', '200009_at', '200010_at', '200011_s_at', '200012_x_at', '200013_at', '200014_s_at', '200015_s_at', '200016_x_at', '200017_at', '200018_at', '200019_s_at', '200020_at', '200021_at', '200022_at', '200023_s_at', '200024_at', '200025_s_at', '200026_at', '200027_at', '200028_s_at', '200029_at', '200030_s_at', '200031_s_at', '200032_s_at', '200033_at', '200034_s_at', '200035_at', '200036_s_at', '200037_s_at', '200038_s_at', '200039_s_at', '200040_at', '200041_s_at', '200042_at', '200043_at', '200044_at', '200045_at', '200046_at', '200047_s_at', '200048_s_at', '200049_at', '200050_at', '200051_at', '200052_s_at', '200053_at', '200054_at', '200055_at', '200056_s_at', '200057_s_at', '200058_s_at', '200059_s_at', '200060_s_at', '200061_s_at', '200062_s_at', '200063_s_at', '200064_at', '200065_s_at', '200066_at', '200067_x_at', '200068_s_at', '200069_at', '200070_at', '200071_at', '200072_s_at', '200073_s_at', '200074_s_at', '200075_s_at', '200076_s_at', '200077_s_at', '200078_s_at', '200079_s_at', '200080_s_at', '200081_s_at', '200082_s_at', '200083_at', '200084_at', '200085_s_at', '200086_s_at', '200087_s_at', '200088_x_at', '200089_s_at', '200090_at', '200091_s_at', '200092_s_at', '200093_s_at', '200094_s_at', '200095_x_at', '200096_s_at', '200097_s_at', '200098_s_at', '200099_s_at', '200593_s_at', '200594_x_at', '200595_s_at', '200596_s_at', '200597_at', '200598_s_at', '200599_s_at', '200600_at', '200601_at', '200602_at', '200603_at', '200604_s_at', '200605_s_at', '200606_at', '200607_s_at', '200608_s_at', '200609_s_at', '200610_s_at', '200611_s_at', '200612_s_at', '200613_at', '200614_at', '200615_s_at', '200616_s_at', '200617_at', '200618_at', '200619_at', '200620_at', '200621_at', '200622_x_at', '200623_s_at', '200624_s_at', '200625_s_at', '200626_s_at', '200627_at', '200628_s_at', '200629_at', '200630_x_at', '200631_s_at', '200632_s_at', '200633_at', '200634_at', '200635_s_at', '200636_s_at', '200637_s_at', '200638_s_at', '200639_s_at', '200640_at', '200641_s_at', '200642_at', '200643_at', '200644_at', '200645_at', '200646_s_at', '200647_x_at', '200648_s_at', '200649_at', '200650_s_at', '200651_at', '200652_at', '200653_s_at', '200654_at', '200655_s_at', '200656_s_at', '200657_at', '200658_s_at', '200659_s_at', '200660_at', '200661_at', '200662_s_at', '200663_at', '200664_s_at', '200665_s_at', '200666_s_at', '200667_at', '200668_s_at', '200669_s_at', '200670_at', '200671_s_at', '200672_x_at', '200673_at', '200674_s_at', '200675_at', '200676_s_at', '200677_at', '200678_x_at', '200679_x_at', '200680_x_at', '200681_at', '200682_s_at', '200683_s_at', '200684_s_at', '200685_at', '200686_s_at', '200687_s_at', '200688_at', '200689_x_at', '200690_at', '200691_s_at', '200692_s_at', '200693_at', '200694_s_at', '200695_at', '200696_s_at', '200697_at', '200698_at', '200699_at', '200700_s_at', '200701_at', '200702_s_at', '200703_at', '200704_at', '200705_s_at', '200706_s_at', '200707_at', '200708_at', '200709_at', '200710_at', '200711_s_at', '200712_s_at', '200713_s_at', '200714_x_at', '200715_x_at', '200716_x_at', '200717_x_at', '200718_s_at', '200719_at', '200720_s_at', '200721_s_at', '200722_s_at', '200723_s_at', '200724_at', '200725_x_at', '200726_at', '200727_s_at', '200728_at', '200729_s_at', '200730_s_at', '200731_s_at', '200732_s_at', '200733_s_at', '200734_s_at', '200735_x_at', '200736_s_at', '200737_at', '200738_s_at', '200739_s_at', '200740_s_at', '200741_s_at', '200742_s_at', '200743_s_at', '200744_s_at', '200745_s_at', '200746_s_at', '200747_s_at', '200748_s_at', '200749_at', '200750_s_at', '200751_s_at', '200752_s_at', '200753_x_at', '200754_x_at', '200755_s_at', '200756_x_at', '200757_s_at', '200758_s_at', '200759_x_at', '200760_s_at', '200761_s_at', '200762_at', '200763_s_at', '200764_s_at', '200765_x_at', '200766_at', '200767_s_at', '200768_s_at', '200769_s_at', '200770_s_at', '200771_at', '200772_x_at', '200773_x_at', '200774_at', '200775_s_at', '200776_s_at', '200777_s_at', '200778_s_at', '200779_at', '200780_x_at', '200781_s_at', '200782_at', '200783_s_at', '200784_s_at', '200785_s_at', '200786_at', '200787_s_at', '200788_s_at', '200789_at', '200790_at', '200791_s_at', '200792_at', '200793_s_at', '200794_x_at', '200795_at', '200796_s_at', '200797_s_at', '200798_x_at', '200799_at', '200800_s_at', '200801_x_at', '200802_at', '200803_s_at', '200804_at', '200805_at', '200806_s_at', '200807_s_at', '200808_s_at', '200809_x_at', '200810_s_at', '200811_at', '200812_at', '200813_s_at', '200814_at', '200815_s_at', '200816_s_at', '200817_x_at', '200818_at', '200819_s_at', '200820_at', '200821_at', '200822_x_at', '200823_x_at', '200824_at', '200825_s_at', '200826_at', '200827_at', '200828_s_at', '200829_x_at', '200830_at', '200831_s_at', '200832_s_at', '200833_s_at', '200834_s_at', '200835_s_at', '200836_s_at', '200837_at', '200838_at', '200839_s_at', '200840_at', '200841_s_at', '200842_s_at', '200843_s_at', '200844_s_at', '200845_s_at', '200846_s_at', '200847_s_at', '200848_at', '200849_s_at', '200850_s_at', '200851_s_at', '200852_x_at', '200853_at', '200854_at', '200855_at', '200856_x_at', '200857_s_at', '200858_s_at', '200859_x_at', '200860_s_at', '200861_at', '200862_at', '200863_s_at', '200864_s_at', '200865_at', '200866_s_at', '200867_at', '200868_s_at', '200869_at', '200870_at', '200871_s_at', '200872_at', '200873_s_at', '200874_s_at', '200875_s_at', '200876_s_at', '200877_at', '200878_at', '200879_s_at', '200880_at', '200881_s_at', '200882_s_at', '200883_at', '200884_at', '200885_at', '200886_s_at', '200887_s_at', '200888_s_at', '200889_s_at', '200890_s_at', '200891_s_at', '200892_s_at', '200893_at', '200894_s_at', '200895_s_at', '200896_x_at', '200897_s_at', '200898_s_at', '200899_s_at', '200900_s_at', '200901_s_at', '200902_at', '200903_s_at', '200904_at', '200905_x_at', '200906_s_at', '200907_s_at', '200908_s_at', '200909_s_at', '200910_at', '200911_s_at', '200912_s_at', '200913_at', '200914_x_at', '200915_x_at', '200916_at', '200917_s_at', '200918_s_at', '200919_at', '200920_s_at', '200921_s_at', '200922_at', '200923_at', '200924_s_at', '200925_at', '200926_at', '200927_s_at', '200928_s_at', '200929_at', '200930_s_at', '200931_s_at', '200932_s_at', '200933_x_at', '200934_at', '200935_at', '200936_at', '200937_s_at', '200938_s_at', '200939_s_at', '200940_s_at', '200941_at', '200942_s_at', '200943_at', '200944_s_at', '200945_s_at', '200946_x_at', '200947_s_at', '200948_at', '200949_x_at', '200950_at', '200951_s_at', '200952_s_at', '200953_s_at', '200954_at', '200955_at', '200956_s_at', '200957_s_at', '200958_s_at', '200959_at', '200960_x_at', '200961_at', '200962_at', '200963_x_at', '200964_at', '200965_s_at', '200966_x_at', '200967_at', '200968_s_at', '200969_at', '200970_s_at', '200971_s_at', '200972_at', '200973_s_at', '200974_at', '200975_at', '200976_s_at', '200977_s_at', '200978_at', '200979_at', '200980_s_at', '200981_x_at', '200982_s_at', '200983_x_at', '200984_s_at', '200985_s_at', '200986_at', '200987_x_at', '200988_s_at', '200989_at', '200990_at', '200991_s_at', '200992_at', '200993_at', '200994_at', '200995_at', '200996_at', '200997_at', '200998_s_at', '200999_s_at', '201000_at', '201001_s_at', '201002_s_at', '201003_x_at', '201004_at', '201005_at', '201006_at', '201007_at', '201008_s_at', '201009_s_at', '201010_s_at', '201011_at', '201012_at', '201013_s_at', '201014_s_at', '201015_s_at', '201016_at', '201017_at', '201018_at', '201019_s_at', '201020_at', '201021_s_at', '201022_s_at', '201023_at', '201024_x_at', '201025_at', '201026_at', '201027_s_at', '201028_s_at', '201029_s_at', '201030_x_at', '201031_s_at', '201032_at', '201033_x_at', '201034_at', '201035_s_at', '201036_s_at', '201037_at', '201038_s_at', '201039_s_at', '201040_at', '201041_s_at', '201042_at', '201043_s_at', '201044_x_at', '201045_s_at', '201046_s_at', '201047_x_at', '201048_x_at', '201049_s_at', '201050_at', '201051_at', '201052_s_at', '201053_s_at', '201054_at', '201055_s_at', '201056_at', '201057_s_at', '201058_s_at', '201059_at', '201060_x_at', '201061_s_at', '201062_at', '201063_at', '201064_s_at', '201065_s_at', '201066_at', '201067_at', '201068_s_at', '201069_at', '201070_x_at', '201071_x_at', '201072_s_at', '201073_s_at', '201074_at', '201075_s_at', '201076_at', '201077_s_at', '201078_at', '201079_at', '201080_at', '201081_s_at', '201082_s_at', '201083_s_at', '201084_s_at', '201085_s_at', '201086_x_at', '201087_at', '201088_at', '201089_at', '201090_x_at', '201091_s_at', '201092_at', '201093_x_at', '201094_at', '201095_at', '201096_s_at', '201097_s_at', '201098_at', '201099_at', '201100_s_at', '201101_s_at', '201102_s_at', '201103_x_at', '201104_x_at', '201105_at', '201106_at', '201107_s_at', '201108_s_at', '201109_s_at', '201110_s_at', '201111_at', '201112_s_at', '201113_at', '201114_x_at', '201115_at', '201116_s_at', '201117_s_at', '201118_at', '201119_s_at', '201120_s_at', '201121_s_at', '201122_x_at', '201123_s_at', '201124_at', '201125_s_at', '201126_s_at', '201127_s_at', '201128_s_at', '201129_at', '201130_s_at', '201131_s_at', '201132_at', '201133_s_at', '201134_x_at', '201135_at', '201136_at', '201137_s_at', '201138_s_at', '201139_s_at', '201140_s_at', '201141_at', '201142_at', '201143_s_at', '201144_s_at', '201145_at', '201146_at', '201147_s_at', '201148_s_at', '201149_s_at', '201150_s_at', '201151_s_at', '201152_s_at', '201153_s_at', '201154_x_at', '201155_s_at', '201156_s_at', '201157_s_at', '201158_at', '201159_s_at', '201160_s_at', '201161_s_at', '201162_at', '201163_s_at', '201164_s_at', '201165_s_at', '201166_s_at', '201167_x_at', '201168_x_at', '201169_s_at', '201170_s_at', '201171_at', '201172_x_at', '201173_x_at', '201174_s_at', '201175_at', '201176_s_at', '201177_s_at', '201178_at', '201179_s_at', '201180_s_at', '201181_at', '201182_s_at', '201183_s_at', '201184_s_at', '201185_at', '201186_at', '201187_s_at', '201188_s_at', '201189_s_at', '201190_s_at', '201191_at', '201192_s_at', '201193_at', '201194_at', '201195_s_at', '201196_s_at', '201197_at', '201198_s_at', '201199_s_at', '201200_at', '201201_at', '201202_at', '201203_s_at', '201204_s_at', '201205_at', '201206_s_at', '201207_at', '201208_s_at', '201209_at', '201210_at', '201211_s_at', '201212_at', '201213_at', '201214_s_at', '201215_at', '201216_at', '201217_x_at', '201218_at', '201219_at', '201220_x_at', '201221_s_at', '201222_s_at', '201223_s_at', '201224_s_at', '201225_s_at', '201226_at', '201227_s_at', '201228_s_at', '201229_s_at', '201230_s_at', '201231_s_at', '201232_s_at', '201233_at', '201234_at', '201235_s_at', '201236_s_at', '201237_at', '201238_s_at', '201239_s_at', '201240_s_at', '201241_at', '201242_s_at', '201243_s_at', '201244_s_at', '201245_s_at', '201246_s_at', '201247_at', '201248_s_at', '201249_at', '201250_s_at', '201251_at', '201252_at', '201253_s_at', '201254_x_at', '201255_x_at', '201256_at', '201257_x_at', '201258_at', '201259_s_at', '201260_s_at', '201261_x_at', '201262_s_at', '201263_at', '201264_at', '201265_at', '201266_at', '201267_s_at', '201268_at', '201269_s_at', '201270_x_at', '201271_s_at', '201272_at', '201273_s_at', '201274_at', '201275_at', '201276_at', '201277_s_at', '201278_at', '201279_s_at', '201280_s_at', '201281_at', '201282_at', '201283_s_at', '201284_s_at', '201285_at', '201286_at', '201287_s_at', '201288_at', '201289_at', '201290_at', '201291_s_at', '201292_at', '201293_x_at', '201294_s_at', '201295_s_at', '201296_s_at', '201297_s_at', '201298_s_at', '201299_s_at', '201300_s_at', '201301_s_at', '201302_at', '201303_at', '201304_at', '201305_x_at', '201306_s_at', '201307_at', '201308_s_at', '201309_x_at', '201310_s_at', '201311_s_at', '201312_s_at', '201313_at', '201314_at', '201315_x_at', '201316_at', '201317_s_at', '201318_s_at', '201319_at', '201320_at', '201321_s_at', '201322_at', '201323_at', '201324_at', '201325_s_at', '201326_at', '201327_s_at', '201328_at', '201329_s_at', '201330_at', '201331_s_at', '201332_s_at', '201333_s_at', '201334_s_at', '201335_s_at', '201336_at', '201337_s_at', '201338_x_at', '201339_s_at', '201340_s_at', '201341_at', '201342_at', '201343_at', '201344_at', '201345_s_at', '201346_at', '201347_x_at', '201348_at', '201349_at', '201350_at', '201351_s_at', '201352_at', '201353_s_at', '201354_s_at', '201355_s_at', '201356_at', '201357_s_at', '201358_s_at', '201359_at', '201360_at', '201361_at', '201362_at', '201363_s_at', '201364_s_at', '201365_at', '201366_at', '201367_s_at', '201368_at', '201369_s_at', '201370_s_at', '201371_s_at', '201372_s_at', '201373_at', '201374_x_at', '201375_s_at', '201376_s_at', '201377_at', '201378_s_at', '201379_s_at', '201380_at', '201381_x_at', '201382_at', '201383_s_at', '201384_s_at', '201385_at', '201386_s_at', '201387_s_at', '201388_at', '201389_at', '201390_s_at', '201391_at', '201392_s_at', '201393_s_at', '201394_s_at', '201395_at', '201396_s_at', '201397_at', '201398_s_at', '201399_s_at', '201400_at', '201401_s_at', '201402_at', '201403_s_at', '201404_x_at', '201405_s_at', '201406_at', '201407_s_at', '201408_at', '201409_s_at', '201410_at', '201411_s_at', '201412_at', '201413_at', '201414_s_at', '201415_at', '201416_at', '201417_at', '201418_s_at', '201419_at', '201420_s_at', '201421_s_at', '201422_at', '201423_s_at', '201424_s_at', '201425_at', '201426_s_at', '201427_s_at', '201428_at', '201429_s_at', '201430_s_at', '201431_s_at', '201432_at', '201433_s_at', '201434_at', '201435_s_at', '201436_at', '201437_s_at', '201438_at', '201439_at', '201440_at', '201441_at', '201442_s_at', '201443_s_at', '201444_s_at', '201445_at', '201446_s_at', '201447_at', '201448_at', '201449_at', '201450_s_at', '201451_x_at', '201452_at', '201453_x_at', '201454_s_at', '201455_s_at', '201456_s_at', '201457_x_at', '201458_s_at', '201459_at', '201460_at', '201461_s_at', '201462_at', '201463_s_at', '201464_x_at', '201465_s_at', '201466_s_at', '201467_s_at', '201468_s_at', '201469_s_at', '201470_at', '201471_s_at', '201472_at', '201473_at', '201474_s_at', '201475_x_at', '201476_s_at', '201477_s_at', '201478_s_at', '201479_at', '201480_s_at', '201481_s_at', '201482_at', '201483_s_at', '201484_at', '201485_s_at', '201486_at', '201487_at', '201488_x_at', '201489_at', '201490_s_at', '201491_at', '201492_s_at', '201493_s_at', '201494_at', '201495_x_at', '201496_x_at', '201497_x_at', '201498_at', '201499_s_at', '201500_s_at', '201501_s_at', '201502_s_at', '201503_at', '201504_s_at', '201505_at', '201506_at', '201507_at', '201508_at', '201509_at', '201510_at', '201511_at', '201512_s_at', '201513_at', '201514_s_at', '201515_s_at', '201516_at', '201517_at', '201518_at', '201519_at', '201520_s_at', '201521_s_at', '201522_x_at', '201523_x_at', '201524_x_at', '201525_at', '201526_at', '201527_at', '201528_at', '201529_s_at', '201530_x_at', '201531_at', '201532_at', '201533_at', '201534_s_at', '201535_at', '201536_at', '201537_s_at', '201538_s_at', '201539_s_at', '201540_at', '201541_s_at', '201542_at', '201543_s_at', '201544_x_at', '201545_s_at', '201546_at', '201547_at', '201548_s_at', '201549_x_at', '201550_x_at', '201551_s_at', '201552_at', '201553_s_at', '201554_x_at', '201555_at', '201556_s_at', '201557_at', '201558_at', '201559_s_at', '201560_at', '201561_s_at', '201562_s_at', '201563_at', '201564_s_at', '201565_s_at', '201566_x_at', '201567_s_at', '201568_at', '201569_s_at', '201570_at', '201571_s_at', '201572_x_at', '201573_s_at', '201574_at', '201575_at', '201576_s_at', '201577_at', '201578_at', '201579_at', '201580_s_at', '201581_at', '201582_at', '201583_s_at', '201584_s_at', '201585_s_at', '201586_s_at', '201587_s_at', '201588_at', '201589_at', '201590_x_at', '201591_s_at', '201592_at', '201593_s_at', '201594_s_at', '201595_s_at', '201596_x_at', '201597_at', '201598_s_at', '201599_at', '201600_at', '201601_x_at', '201602_s_at', '201603_at', '201604_s_at', '201605_x_at', '201606_s_at', '201607_at', '201608_s_at', '201609_x_at', '201610_at', '201611_s_at', '201612_at', '201613_s_at', '201614_s_at', '201615_x_at', '201616_s_at', '201617_x_at', '201618_x_at', '201619_at', '201620_at', '201621_at', '201622_at', '201623_s_at', '201624_at', '201625_s_at', '201626_at', '201627_s_at', '201628_s_at', '201629_s_at', '201630_s_at', '201631_s_at', '201632_at', '201633_s_at', '201634_s_at', '201635_s_at', '201636_at', '201637_s_at', '201638_s_at', '201639_s_at', '201640_x_at', '201641_at', '201642_at', '201643_x_at', '201644_at', '201645_at', '201646_at', '201647_s_at', '201648_at', '201649_at', '201650_at', '201651_s_at', '201652_at', '201653_at', '201654_s_at', '201655_s_at', '201656_at', '201657_at', '201658_at', '201659_s_at', '201660_at', '201661_s_at', '201662_s_at', '201663_s_at', '201664_at', '201665_x_at', '201666_at', '201667_at', '201668_x_at', '201669_s_at', '201670_s_at', '201671_x_at', '201672_s_at', '201673_s_at', '201674_s_at', '201675_at', '201676_x_at', '201677_at', '201678_s_at', '201679_at', '201680_x_at', '201681_s_at', '201682_at', '201683_x_at', '201684_s_at', '201685_s_at', '201686_x_at', '201687_s_at', '201688_s_at', '201689_s_at', '201690_s_at', '201691_s_at', '201692_at', '201693_s_at', '201694_s_at', '201695_s_at', '201696_at', '201697_s_at', '201698_s_at', '201699_at', '201700_at', '201701_s_at', '201702_s_at', '201703_s_at', '201704_at', '201705_at', '201706_s_at', '201707_at', '201708_s_at', '201709_s_at', '201710_at', '201711_x_at', '201712_s_at', '201713_s_at', '201714_at', '201715_s_at', '201716_at', '201717_at', '201718_s_at', '201719_s_at', '201720_s_at', '201721_s_at', '201722_s_at', '201723_s_at', '201724_s_at', '201725_at', '201726_at', '201727_s_at', '201728_s_at', '201729_s_at', '201730_s_at', '201731_s_at', '201732_s_at', '201733_at', '201734_at', '201735_s_at', '201736_s_at', '201737_s_at', '201738_at', '201739_at', '201740_at', '201741_x_at', '201742_x_at', '201743_at', '201744_s_at', '201745_at', '201746_at', '201747_s_at', '201748_s_at', '201749_at', '201750_s_at', '201751_at', '201752_s_at', '201753_s_at', '201754_at', '201755_at', '201756_at', '201757_at', '201758_at', '201759_at', '201760_s_at', '201761_at', '201762_s_at', '201763_s_at', '201764_at', '201765_s_at', '201766_at', '201767_s_at', '201768_s_at', '201769_at', '201770_at', '201771_at', '201772_at', '201773_at', '201774_s_at', '201775_s_at', '201776_s_at', '201777_s_at', '201778_s_at', '201779_s_at', '201780_s_at', '201781_s_at', '201782_s_at', '201783_s_at', '201784_s_at', '201785_at', '201786_s_at', '201787_at', '201788_at', '201789_at', '201790_s_at', '201791_s_at', '201792_at', '201793_x_at', '201794_s_at', '201795_at', '201796_s_at', '201797_s_at', '201798_s_at', '201799_s_at', '201800_s_at', '201801_s_at', '201802_at', '201803_at', '201804_x_at', '201805_at', '201806_s_at', '201807_at', '201808_s_at', '201809_s_at', '201810_s_at', '201811_x_at', '201812_s_at', '201813_s_at', '201814_at', '201815_s_at', '201816_s_at', '201817_at', '201818_at', '201819_at', '201820_at', '201821_s_at', '201822_at', '201823_s_at', '201824_at', '201825_s_at', '201826_s_at', '201827_at', '201828_x_at', '201829_at', '201830_s_at', '201831_s_at', '201832_s_at', '201833_at', '201834_at', '201835_s_at', '201836_s_at', '201837_s_at', '201838_s_at', '201839_s_at', '201840_at', '201841_s_at', '201842_s_at', '201843_s_at', '201844_s_at', '201845_s_at', '201846_s_at', '201847_at', '201848_s_at', '201849_at', '201850_at', '201851_at', '201852_x_at', '201853_s_at', '201854_s_at', '201855_s_at', '201856_s_at', '201857_at', '201858_s_at', '201859_at', '201860_s_at', '201861_s_at', '201862_s_at', '201863_at', '201864_at', '201865_x_at', '201866_s_at', '201867_s_at', '201868_s_at', '201869_s_at', '201870_at', '201871_s_at', '201872_s_at', '201873_s_at', '201874_at', '201875_s_at', '201876_at', '201877_s_at', '201878_at', '201879_at', '201880_at',

In [47]:
iden_probe = iden_probe.drop(0)

In [31]:
# 1. ดึงชื่อคอลัมน์ออกมาเป็น List (เพื่อให้แก้ไขได้)
new_cols = list(df_target.columns)

for i in range(len(df_identifier.columns)):
    if i < len(df_target.columns):
        # 2. เปรียบเทียบชื่อคอลัมน์เดิม
        if df_identifier.columns[i] == df_target.columns[i]:
            # 3. เก็บค่าใหม่จากแถวที่ 0 ของ identifier ลงใน List
            new_cols[i] = df_identifier.iloc[0, i]

# 4. อัปเดตชื่อคอลัมน์ทั้งหมดกลับไปที่ df_target
df_target.columns = new_cols

In [15]:
df_identifier.iloc[0, :]

Unnamed: 0         IDENTIFIER
1007_s_at             MIR4640
1053_at                  RFC2
117_at                  HSPA6
121_at                   PAX8
                      ...
AFFX-ThrX-5_at      --Control
AFFX-ThrX-M_at      --Control
AFFX-TrpnX-3_at     --Control
AFFX-TrpnX-5_at     --Control
AFFX-TrpnX-M_at     --Control
Name: 0, Length: 22284, dtype: object

In [14]:
df_target.iloc[0, :]

Unnamed: 0         GSM254629
1007_s_at            10.9885
1053_at              6.82603
117_at               7.77559
121_at               9.85506
                     ...
AFFX-ThrX-M_at       4.58001
AFFX-TrpnX-3_at      4.06666
AFFX-TrpnX-5_at      4.63296
AFFX-TrpnX-M_at      4.63396
target                 tumor
Name: 0, Length: 22285, dtype: object

In [33]:
df_target.to_csv('new_target.csv', index=False)

In [50]:
# เอา df2 มาแปะข้าง df1
result_m1 = pd.concat([iden, iden_probe], axis=1)

In [ ]:
result_m1[]

      IDENTIFIER        prob_iden
1        MIR4640        1007_s_at
2           RFC2          1053_at
3          HSPA6           117_at
4           PAX8           121_at
5         GUCA1A        1255_g_at
...          ...              ...
22279  --Control   AFFX-ThrX-5_at
22280  --Control   AFFX-ThrX-M_at
22281  --Control  AFFX-TrpnX-3_at
22282  --Control  AFFX-TrpnX-5_at
22283  --Control  AFFX-TrpnX-M_at

[22283 rows x 2 columns]

In [56]:
tar_get = tar_get.rename(columns={"probe": "prob_iden"})

In [58]:
result = pd.merge(tar_get, result_m1, on='prob_iden', how='inner')

In [59]:
result

             prob_iden IDENTIFIER
0            1007_s_at    MIR4640
1              1053_at       RFC2
2               117_at      HSPA6
3               121_at       PAX8
4            1255_g_at     GUCA1A
...                ...        ...
22278   AFFX-ThrX-5_at  --Control
22279   AFFX-ThrX-M_at  --Control
22280  AFFX-TrpnX-3_at  --Control
22281  AFFX-TrpnX-5_at  --Control
22282  AFFX-TrpnX-M_at  --Control

[22283 rows x 2 columns]

In [60]:
result.to_csv("map_probe.csv", header=False, index=False)

In [69]:
sum_df = pd.read_csv(r'C:\Users\User\Documents\GitHub\AIforBioinformatics\ignore_dir\dataset\summary_results.csv')
sum_df

,Model,Optimal_Features,LOOCV_Accuracy,Precision (Avg),Recall (Avg),F1-Score (Avg),Selected_Genes
0,Perceptron,25,0.950,0.9497,0.9497,0.9497,"209875_s_at, 215454_x_at, 210081_at, 204273_at..."
1,SVC_Linear,1,1.000,1.0000,1.0000,1.0000,209555_s_at
2,Logistic_Reg,4,0.975,0.9778,0.9730,0.9747,"209875_s_at, 206488_s_at, 218469_at, 203296_s_at"

In [68]:
sum_df['Selected_Genes'][2]

'209875_s_at, 206488_s_at, 218469_at, 203296_s_at'

In [71]:
import pandas as pd

# 1. โหลดไฟล์ CSV (เปลี่ยน 'map_file.csv' เป็นชื่อไฟล์จริงของคุณ)
# header=None คือไม่มีหัวตาราง, names คือเราตั้งชื่อคอลัมน์เองให้เรียกง่าย
df_map = pd.read_csv(r'C:\Users\User\Documents\GitHub\AIforBioinformatics\ignore_dir\dataset\map_probe.csv', header=None, names=['probe', 'gene'])

# 2. แปลงเป็น Dictionary { '1007_s_at': 'MIR4640', ... }
mapping_dict = dict(zip(df_map['probe'], df_map['gene']))

In [74]:
def map_selected_genes(text):
    if pd.isna(text):
        return text
    
    # แยก ID ออกจากกัน (และตัดช่องว่างทิ้ง)
    ids = [i.strip() for i in text.split(',')]
    
    # เอาแต่ละ ID ไปเทียบใน dict ถ้าไม่เจอให้ใช้ ID เดิม (ป้องกันข้อมูลหาย)
    translated = [mapping_dict.get(i, i) for i in ids]
    
    # รวมกลับเป็น string เดียวกัน คั่นด้วยคอมม่าเหมือนเดิม
    return ", ".join(translated)

# นำไปใช้งานกับ DataFrame หลักของคุณ (สมมติชื่อ df)
sum_df['Selected_Genes'] = sum_df['Selected_Genes'].apply(map_selected_genes)

In [75]:
sum_df

,Model,Optimal_Features,LOOCV_Accuracy,Precision (Avg),Recall (Avg),F1-Score (Avg),Selected_Genes
0,Perceptron,25,0.950,0.9497,0.9497,0.9497,"SPP1, SFTPC, AGER, EDNRB, EXOSC7, ABCA8, GREM1..."
1,SVC_Linear,1,1.000,1.0000,1.0000,1.0000,CD36
2,Logistic_Reg,4,0.975,0.9778,0.9730,0.9747,"SPP1, CD36, GREM1, ATP1A2"